import { beforeEach, describe, expect, it, vi } from 'vitest'
import { mountSuspended, mockNuxtImport } from '@nuxt/test-utils/runtime'
import { flushPromises } from '@vue/test-utils'
import { ref } from 'vue'
import ActivityDetailPage from './[id].vue'
import ActivityStatusBadges from '~/components/activity/ActivityStatusBadges.vue'
import type { ActivityDetailResponse } from '~/types/activity'

const mocks = vi.hoisted(() => ({ getActivity: vi.fn(), metadata: vi.fn(), error: vi.fn() }))
mockNuxtImport('useRoute', () => () => ({ params: { id: '7' } }))
mockNuxtImport('useI18n', () => () => ({ t: (key: string) => key }))
mockNuxtImport('useActivityApi', () => () => ({
  getActivity: mocks.getActivity,
  publishActivity: vi.fn(),
}))
mockNuxtImport('useFileSharingApi', () => () => ({
  getFileMetadata: mocks.metadata,
  getDownloadUrl: vi.fn(),
}))
mockNuxtImport('useErrorHandler', () => () => ({ handleApiError: mocks.error }))
mockNuxtImport('useNotification', () => () => ({ success: vi.fn() }))
mockNuxtImport('useMarkdownRenderer', () => () => ({ renderMarkdown: (value: string) => value }))
mockNuxtImport('useActivityDeletion', () => () => ({
  deleting: ref(false),
  requestDelete: vi.fn(),
}))

function record(overrides: Partial<ActivityDetailResponse> = {}): ActivityDetailResponse {
  return {
    id: 7,
    scopeType: 'TEAM',
    scopeId: 1,
    scopePublicId: 'own-team',
    templateId: null,
    title: 'visible schedule',
    activityDate: '2026-10-08',
    activityEndDate: null,
    activityTimeStart: '09:00:30',
    activityTimeEnd: '10:00:30',
    location: null,
    venueId: null,
    description: 'private description',
    fieldValues: '{"privateResult":0}',
    attachments: null,
    visibility: 'MEMBERS_ONLY',
    status: 'DRAFT',
    scheduleId: 2,
    createdBy: 3,
    createdAt: '2026-10-08T00:00:00',
    updatedAt: '2026-10-08T00:00:00',
    version: 0,
    autoGeneratedFromSchedule: true,
    isPlanned: true,
    metadataOnly: false,
    canEdit: true,
    canPublish: true,
    canDelete: true,
    sourceSchedule: {
      scopeType: 'TEAM',
      scopeId: 1,
      scopePublicId: 'own-team',
      id: 2,
      state: 'AVAILABLE',
      canView: true,
    },
    participants: [
      {
        id: 1,
        userId: 3,
        displayName: 'private participant',
        memberNumber: null,
        roleLabel: null,
        createdAt: '2026-10-08T00:00:00',
      },
    ],
    templateFields: [],
    ...overrides,
  }
}
const options = {
  global: {
    stubs: {
      ActivityStatusBadges,
      PageHeader: { props: ['title'], template: '<h1>{{ title }}</h1>' },
      SectionCard: { props: ['title'], template: '<section>{{ title }}<slot /></section>' },
      Tag: { props: ['value'], template: '<span>{{ value }}</span>' },
      Button: { props: ['label'], template: '<button>{{ label }}</button>' },
      NuxtLink: { props: ['to'], template: '<a :href="to"><slot /></a>' },
      ActivityEditDialog: true,
      DashboardEmptyState: true,
      PageLoading: true,
      DashboardErrorState: true,
    },
  },
}

describe('活動詳細の予定metadata表示', () => {
  beforeEach(() => vi.clearAllMocks())
  it.each([true, false])(
    '予定フラグ%sでも未公開案内を保ち実績欄と能力操作を表示しない',
    async (isPlanned) => {
      mocks.getActivity.mockResolvedValue({
        data: record({
          metadataOnly: true,
          version: null,
          createdAt: null,
          updatedAt: null,
          isPlanned,
          canEdit: false,
          canPublish: false,
          canDelete: false,
          fieldValues: 'invalid private JSON',
          attachments: '{"file_ids":[10]}',
        }),
      })
      const wrapper = await mountSuspended(ActivityDetailPage, options)
      await flushPromises()
      expect(wrapper.text()).toContain('visible schedule')
      expect(wrapper.text()).toContain('activity.metadataOnly')
      expect(wrapper.text()).toContain('activity.unpublished')
      expect(wrapper.find('[data-testid="activity-planned-7"]').exists()).toBe(isPlanned)
      for (const selector of [
        'activity-description',
        'activity-template-fields',
        'activity-participants',
        'activity-edit-draft',
        'activity-publish',
        'activity-delete',
      ]) {
        expect(wrapper.find(`[data-testid="${selector}"]`).exists()).toBe(false)
      }
      expect(wrapper.text()).not.toContain('private')
      expect(wrapper.text()).not.toContain('activity.detail.noParticipants')
      expect(mocks.metadata).not.toHaveBeenCalled()
      expect(mocks.error).not.toHaveBeenCalled()
      expect(wrapper.find('[data-testid="activity-source-schedule"]').attributes('href')).toBe(
        '/teams/own-team/schedule?eventId=2',
      )
    },
  )
  it('元予定参照不可でも編集者の保存済み実績と削除能力を保持する', async () => {
    mocks.getActivity.mockResolvedValue({
      data: record({
        isPlanned: false,
        sourceSchedule: {
          scopeType: null,
          scopeId: null,
          scopePublicId: null,
          id: null,
          state: 'UNAVAILABLE',
          canView: false,
        },
      }),
    })
    const wrapper = await mountSuspended(ActivityDetailPage, options)
    await flushPromises()
    expect(wrapper.text()).toContain('private description')
    expect(wrapper.text()).toContain('private participant')
    expect(wrapper.find('[data-testid="activity-edit-draft"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="activity-delete"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="activity-source-schedule"]').exists()).toBe(false)
    expect(wrapper.text()).toContain('activity.detail.scheduleUnavailable')
    expect(wrapper.find('[data-testid="activity-planned-7"]').exists()).toBe(false)
    expect(wrapper.text()).toContain('activity.unpublished')
  })
  it('公開済み記録も削除能力に従い、未依頼の公開後編集導線を増やさない', async () => {
    mocks.getActivity.mockResolvedValue({
      data: record({ status: 'PUBLISHED', canPublish: false }),
    })
    const wrapper = await mountSuspended(ActivityDetailPage, options)
    await flushPromises()
    expect(wrapper.find('[data-testid="activity-delete"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="activity-edit-draft"]').exists()).toBe(false)
    expect(wrapper.text()).toContain('activity.statusLabel.PUBLISHED')
  })
})
