import Aura from '@primeuix/themes/aura'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },

  app: {
    head: {
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1',
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap',
        },
      ],
    },
    pageTransition: { name: 'page-fade', mode: 'out-in' },
  },
  future: {
    compatibilityVersion: 4,
  },

  components: [{ path: '~/components', pathPrefix: false }],

  imports: {
    dirs: ['composables', 'composables/jobs', 'composables/wallet-group-show'],
  },

  devServer: {
    host: '0.0.0.0',
  },

  modules: [
    '@nuxtjs/i18n',
    '@primevue/nuxt-module',
    '@nuxtjs/tailwindcss',
    '@pinia/nuxt',
    '@vueuse/nuxt',
    '@nuxt/image',
    '@nuxt/eslint',
    '@vite-pwa/nuxt',
  ],

  pwa: {
    registerType: 'autoUpdate',
    manifest: {
      name: 'Mannschaft',
      short_name: 'Mannschaft',
      description: '汎用組織管理プラットフォーム',
      lang: 'ja',
      theme_color: '#3B82F6',
      background_color: '#ffffff',
      display: 'standalone',
      start_url: '/',
      icons: [
        { src: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
        { src: '/icons/icon-512x512.png', sizes: '512x512', type: 'image/png' },
        {
          src: '/icons/icon-512x512.png',
          sizes: '512x512',
          type: 'image/png',
          purpose: 'maskable',
        },
      ],
      // Androidホーム画面アイコン長押しメニュー（ショートカット）
      shortcuts: [
        {
          name: 'ポイっとメモ',
          short_name: 'メモ',
          description: 'すぐにメモを入力する',
          url: '/quick-memos',
          icons: [{ src: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' }],
        },
      ],
    },
    workbox: {
      navigateFallback: '/',
      globPatterns: ['**/*.{js,css,html,png,svg,ico,woff2}'],
      runtimeCaching: [
        {
          urlPattern: /^https?:\/\/.*\/api\/v1\/.*$/,
          handler: 'StaleWhileRevalidate' as const,
          method: 'GET',
          options: {
            cacheName: 'api-cache',
            expiration: { maxEntries: 200, maxAgeSeconds: 86400 },
            cacheableResponse: { statuses: [0, 200] },
          },
        },
        {
          urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
          handler: 'CacheFirst' as const,
          options: {
            cacheName: 'image-cache',
            expiration: { maxEntries: 300, maxAgeSeconds: 604800 },
            cacheableResponse: { statuses: [0, 200] },
          },
        },
        {
          urlPattern: /\.(?:woff|woff2|ttf|eot)$/,
          handler: 'CacheFirst' as const,
          options: {
            cacheName: 'font-cache',
            expiration: { maxEntries: 20, maxAgeSeconds: 2592000 },
          },
        },
      ],
    },
  },

  css: [
    '~/assets/css/main.css',
    // frappe-gantt v1.2.2 の package.json exports に CSS サブパスが未定義のため、
    // Vite が exports を厳密チェックして ERR_PACKAGE_PATH_NOT_EXPORTED になる問題を回避。
    // node_modules からアセットとしてコピーし、exports 制限を完全に回避する（意図的なベンダリング）。
    '~/assets/css/frappe-gantt.css',
  ],

  runtimeConfig: {
    // F10.6 Phase 10-γ-③-b: SSRエラー転送用内部トークン（サーバーサイドのみ）
    internalLogToken: process.env.NUXT_INTERNAL_LOG_TOKEN || 'dev-internal-token',
    public: {
      apiBase: process.env.NUXT_PUBLIC_API_BASE ?? 'http://localhost:8080',
      // F18 SELF_ISSUED_BALANCE 機能フラグ（2026-05-17 マスター御裁可で凍結）。
      // 資金決済法（前払式支払手段＝自家型）対応のため法務整備が整うまで一時凍結。
      // 設計書: docs/features/F18_point_card_wallet.md §1.4 / §16 / §17
      // 既定 false（凍結中）。再開時は NUXT_PUBLIC_F18_BALANCE_ENABLED=true で復活可能。
      f18BalanceEnabled: process.env.NUXT_PUBLIC_F18_BALANCE_ENABLED === 'true',
    },
  },

  // E2E テスト時（NUXT_API_PROXY=true 環境変数）は API を Nuxt サーバー経由でプロキシする。
  // これにより CORS プリフライト問題を回避し、Playwright のルートインターセプトが確実に機能する。
  routeRules: process.env.NUXT_API_PROXY === 'true' ? {
    '/api/v1/**': { proxy: 'http://localhost:8080/api/v1/**' },
  } : {},

  i18n: {
    locales: [
      {
        code: 'ja',
        language: 'ja',
        name: '日本語',
        files: [
          'ja/common.json',
          'ja/auth.json',
          'ja/validation.json',
          'ja/landing.json',
          'ja/help.json',
          'ja/action_memo.json',
          'ja/pwa.json',
          'ja/recruitment.ts',
          'ja/quick_memo.json',
          'ja/timeline_digest.json',
          'ja/translation.json',
          'ja/equipment.json',
          'ja/friends.json',
          'ja/announcement.json',
          'ja/profile_media.json',
          'ja/appearance.json',
          'ja/event.json',
          'ja/committee.json',
          'ja/jobmatching.json',
          'ja/shift.json',
          'ja/care.json',
          'ja/surveys.json',
          'ja/reservation.json',
          'ja/school.json',
          'ja/shiftBudget.json',
          'ja/dashboard.json',
          'ja/activity.json',
          'ja/settings.json',
          'ja/timetable.json',
          'ja/member-info.json',
          'ja/property.json',
          'ja/disclosure.json',
          'ja/error_report.json',
          'ja/org_sidebar.json',
          'ja/repair_plan.json',
          'ja/succession.json',
          'ja/wallet.json',
          'ja/village.json',
          'ja/system_admin_batch.json',
          'ja/system_admin_gdpr.json',
          'ja/advertising.json',
          'ja/public.json',
          'ja/proxy.json',
        ],
      },
      {
        code: 'en',
        language: 'en',
        name: 'English',
        files: [
          'en/common.json',
          'en/auth.json',
          'en/validation.json',
          'en/landing.json',
          'en/help.json',
          'en/action_memo.json',
          'en/pwa.json',
          'en/recruitment.ts',
          'en/quick_memo.json',
          'en/timeline_digest.json',
          'en/translation.json',
          'en/equipment.json',
          'en/friends.json',
          'en/announcement.json',
          'en/profile_media.json',
          'en/appearance.json',
          'en/event.json',
          'en/committee.json',
          'en/jobmatching.json',
          'en/shift.json',
          'en/care.json',
          'en/surveys.json',
          'en/reservation.json',
          'en/school.json',
          'en/shiftBudget.json',
          'en/dashboard.json',
          'en/activity.json',
          'en/settings.json',
          'en/timetable.json',
          'en/member-info.json',
          'en/property.json',
          'en/disclosure.json',
          'en/error_report.json',
          'en/org_sidebar.json',
          'en/repair_plan.json',
          'en/succession.json',
          'en/wallet.json',
          'en/village.json',
          'en/system_admin_batch.json',
          'en/system_admin_gdpr.json',
          'en/advertising.json',
          'en/public.json',
          'en/proxy.json',
        ],
      },
      {
        code: 'zh',
        language: 'zh',
        name: '中文（简体）',
        files: [
          'zh/common.json',
          'zh/auth.json',
          'zh/validation.json',
          'zh/landing.json',
          'zh/help.json',
          'zh/action_memo.json',
          'zh/pwa.json',
          'zh/recruitment.ts',
          'zh/quick_memo.json',
          'zh/timeline_digest.json',
          'zh/translation.json',
          'zh/equipment.json',
          'zh/friends.json',
          'zh/announcement.json',
          'zh/profile_media.json',
          'zh/appearance.json',
          'zh/event.json',
          'zh/committee.json',
          'zh/jobmatching.json',
          'zh/shift.json',
          'zh/care.json',
          'zh/surveys.json',
          'zh/reservation.json',
          'zh/school.json',
          'zh/shiftBudget.json',
          'zh/dashboard.json',
          'zh/activity.json',
          'zh/settings.json',
          'zh/timetable.json',
          'zh/member-info.json',
          'zh/property.json',
          'zh/disclosure.json',
          'zh/error_report.json',
          'zh/org_sidebar.json',
          'zh/repair_plan.json',
          'zh/succession.json',
          'zh/wallet.json',
          'zh/village.json',
          'zh/system_admin_batch.json',
          'zh/system_admin_gdpr.json',
          'zh/advertising.json',
          'zh/public.json',
          'zh/proxy.json',
        ],
      },
      {
        code: 'ko',
        language: 'ko',
        name: '한국어',
        files: [
          'ko/common.json',
          'ko/auth.json',
          'ko/validation.json',
          'ko/landing.json',
          'ko/help.json',
          'ko/action_memo.json',
          'ko/pwa.json',
          'ko/recruitment.ts',
          'ko/quick_memo.json',
          'ko/timeline_digest.json',
          'ko/translation.json',
          'ko/equipment.json',
          'ko/friends.json',
          'ko/announcement.json',
          'ko/profile_media.json',
          'ko/appearance.json',
          'ko/event.json',
          'ko/committee.json',
          'ko/jobmatching.json',
          'ko/shift.json',
          'ko/care.json',
          'ko/surveys.json',
          'ko/reservation.json',
          'ko/school.json',
          'ko/shiftBudget.json',
          'ko/dashboard.json',
          'ko/activity.json',
          'ko/settings.json',
          'ko/timetable.json',
          'ko/member-info.json',
          'ko/property.json',
          'ko/disclosure.json',
          'ko/error_report.json',
          'ko/org_sidebar.json',
          'ko/repair_plan.json',
          'ko/succession.json',
          'ko/wallet.json',
          'ko/village.json',
          'ko/system_admin_batch.json',
          'ko/system_admin_gdpr.json',
          'ko/advertising.json',
          'ko/public.json',
          'ko/proxy.json',
        ],
      },
      {
        code: 'es',
        language: 'es',
        name: 'Español',
        files: [
          'es/common.json',
          'es/auth.json',
          'es/validation.json',
          'es/landing.json',
          'es/help.json',
          'es/action_memo.json',
          'es/pwa.json',
          'es/recruitment.ts',
          'es/quick_memo.json',
          'es/timeline_digest.json',
          'es/translation.json',
          'es/equipment.json',
          'es/friends.json',
          'es/announcement.json',
          'es/profile_media.json',
          'es/appearance.json',
          'es/event.json',
          'es/committee.json',
          'es/jobmatching.json',
          'es/shift.json',
          'es/care.json',
          'es/surveys.json',
          'es/reservation.json',
          'es/school.json',
          'es/shiftBudget.json',
          'es/dashboard.json',
          'es/activity.json',
          'es/settings.json',
          'es/timetable.json',
          'es/member-info.json',
          'es/property.json',
          'es/disclosure.json',
          'es/error_report.json',
          'es/org_sidebar.json',
          'es/repair_plan.json',
          'es/succession.json',
          'es/wallet.json',
          'es/village.json',
          'es/system_admin_batch.json',
          'es/system_admin_gdpr.json',
          'es/advertising.json',
          'es/public.json',
          'es/proxy.json',
        ],
      },
      {
        code: 'de',
        language: 'de',
        name: 'Deutsch',
        files: [
          'de/common.json',
          'de/auth.json',
          'de/validation.json',
          'de/landing.json',
          'de/help.json',
          'de/action_memo.json',
          'de/pwa.json',
          'de/recruitment.ts',
          'de/quick_memo.json',
          'de/timeline_digest.json',
          'de/translation.json',
          'de/equipment.json',
          'de/friends.json',
          'de/announcement.json',
          'de/profile_media.json',
          'de/appearance.json',
          'de/event.json',
          'de/committee.json',
          'de/jobmatching.json',
          'de/shift.json',
          'de/care.json',
          'de/surveys.json',
          'de/reservation.json',
          'de/school.json',
          'de/shiftBudget.json',
          'de/dashboard.json',
          'de/activity.json',
          'de/settings.json',
          'de/timetable.json',
          'de/member-info.json',
          'de/property.json',
          'de/disclosure.json',
          'de/error_report.json',
          'de/org_sidebar.json',
          'de/repair_plan.json',
          'de/succession.json',
          'de/wallet.json',
          'de/village.json',
          'de/system_admin_batch.json',
          'de/system_admin_gdpr.json',
          'de/advertising.json',
          'de/public.json',
          'de/proxy.json',
        ],
      },
    ],
    defaultLocale: 'ja',
    strategy: 'no_prefix',
    lazy: true,
    restructureDir: false,
    bundle: {
      optimizeTranslationDirective: false,
    },
    langDir: 'locales/',
    detectBrowserLanguage: {
      useCookie: false,
      redirectOn: 'root',
    },
  },

  primevue: {
    autoImport: true,
    components: {
      prefix: '',
    },
    options: {
      ripple: true,
      inputVariant: 'filled',
      theme: {
        preset: Aura,
        options: {
          prefix: 'p',
          darkModeSelector: '.p-dark',
          cssLayer: false,
        },
      },
    },
  },

  build: {
    // frappe-gantt 1.2.2 の package.json exports フィールドに
    // ./dist/frappe-gantt.css が列挙されていないため、
    // nuxt:ssr-styles:client プラグインの静的解析時にエラーが発生する。
    // transpile に指定することで Vite がパッケージを直接バンドルし解消する。
    transpile: ['frappe-gantt'],
  },

  // GitHub Actions (CI=true) では SSR バンドルロード自体が 4GB OOM を引き起こすため
  // SPA モード（ssr: false）で Nitro SSR バンドルをスキップする。
  // nuxt generate が index.html + クライアント資産のみ生成し Lighthouse CI で計測可能。
  ...(process.env.CI === 'true' ? { ssr: false } : {}),

  vite: {
    server: {
      allowedHosts: true,
    },
    optimizeDeps: {
      // date-holidays は pure ESM パッケージのため、Vite が事前バンドルしないと
      // dev server の SSR コンテキストでモジュール評価が失敗する
      include: ['date-holidays', 'dexie'],
    },
  },
})
