<script setup lang="ts">
import type { ActivityRecordResponse } from '~/types/activity'
defineProps<{
  record: Pick<ActivityRecordResponse, 'id' | 'status' | 'isPlanned' | 'autoGeneratedFromSchedule'>
}>()
const { t } = useI18n()
</script>

<template>
  <span class="inline-flex flex-wrap items-center gap-2">
    <Tag
      v-if="record.isPlanned"
      :value="t('activity.planned')"
      severity="info"
      :data-testid="`activity-planned-${record.id}`"
    />
    <Tag
      :value="
        t(
          record.autoGeneratedFromSchedule && record.status === 'DRAFT'
            ? 'activity.unpublished'
            : `activity.statusLabel.${record.status}`,
        )
      "
      :severity="record.status === 'DRAFT' ? 'warn' : 'success'"
      :data-testid="`activity-status-${record.id}`"
    />
  </span>
</template>
