package com.mannschaft.app.activity.service;

import com.mannschaft.app.activity.ActivityErrorCode;
import com.mannschaft.app.activity.dto.ActivityDeletionReference;
import com.mannschaft.app.activity.repository.ActivityResultRepository;
import com.mannschaft.app.common.BusinessException;
import com.mannschaft.app.common.CommonErrorCode;
import jakarta.persistence.EntityManager;
import jakarta.persistence.LockModeType;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import java.util.Objects;

/** 共通層で認可・source lock済みのauto活動を削除する純activity writer。 */
@Service
@RequiredArgsConstructor
public class ActivityDeletionService {
    private final ActivityResultRepository results;
    private final EntityManager entityManager;

    @Transactional(propagation = Propagation.MANDATORY)
    public void deleteAutomatic(ActivityDeletionReference expected) {
        var current = results.lockForDeletion(expected.id())
                .orElseThrow(() -> new BusinessException(ActivityErrorCode.ACTIVITY_NOT_FOUND));
        entityManager.refresh(current, LockModeType.PESSIMISTIC_WRITE);
        if (!current.isAutoGeneratedFromSchedule() || !expected.autoGeneratedFromSchedule()
                || !Objects.equals(current.getScopeType().name(), expected.scopeType())
                || !Objects.equals(current.getScopeId(), expected.scopeId())
                || !Objects.equals(current.getScheduleId(), expected.scheduleId())
                || !Objects.equals(current.getVersion(), expected.version())) {
            throw new BusinessException(CommonErrorCode.COMMON_003);
        }
        current.softDelete();
        results.saveAndFlush(current);
    }
}
