package com.mannschaft.app.activity.service;

import com.mannschaft.app.activity.ActivityMapper;
import com.mannschaft.app.activity.ActivityStatus;
import com.mannschaft.app.activity.dto.ActivityDetailResponse;
import com.mannschaft.app.activity.dto.ActivitySourceScheduleResponse;
import com.mannschaft.app.activity.entity.ActivityResultEntity;
import com.mannschaft.app.schedule.service.ScheduleActivitySourceService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Objects;

/** 認証済み詳細に表示用情報を追加する。公開DTO・一覧DTOは変更しない。 */
@Service
@RequiredArgsConstructor
public class ActivityDetailService {
    private final ActivityResultService activityService;
    private final ActivityScopeAccessGuard scopeAccessGuard;
    private final ActivityMapper mapper;
    private final ActivityDetailEnrichmentService enrichment;
    private final ScheduleActivitySourceService scheduleSources;
    private final com.mannschaft.app.activity.repository.ActivityResultRepository results;
    private final com.mannschaft.app.activity.repository.ActivityCommentRepository comments;

    /** 共通段取り役の更新認可。所属・閲覧認可の後に作者／管理者を検証する。 */
    public void requireEditPermission(Long id, Long userId) {
        var activity = activityService.getActivity(id, userId);
        scopeAccessGuard.checkAuthorOrAdmin(userId, activity.getCreatedBy(), activity.getScopeType(), activity.getScopeId());
    }

    public ActivityDetailResponse getDetail(Long id, Long userId) {
        var stored = results.findById(id).orElseThrow(() -> new com.mannschaft.app.common.BusinessException(
                com.mannschaft.app.activity.ActivityErrorCode.ACTIVITY_NOT_FOUND));
        if (stored.isAutoGeneratedFromSchedule()) {
            var source = requireAutomaticAccess(stored, userId, true);
            if (stored.getStatus() == ActivityStatus.DRAFT && source.isPresent()) return metadataDetail(stored, source.get());
        }
        ActivityResultEntity activity = activityService.getActivity(id, userId);
        boolean canEdit = Objects.equals(activity.getCreatedBy(), userId)
                || scopeAccessGuard.isAdminOrAbove(userId, activity.getScopeType(), activity.getScopeId());
        var record = mapper.toActivityRecordResponse(activity);
        var related = enrichment.enrich(record);
        ActivitySourceScheduleResponse source = activity.getScheduleId() == null ? null
                : scheduleSources.visibleSource(activity.getScheduleId(), userId)
                .filter(s -> activity.getScopeType().name().equals(s.scopeType()) && Objects.equals(activity.getScopeId(), s.scopeId()))
                .map(s -> new ActivitySourceScheduleResponse(s.scopeType(), s.scopeId(),
                        enrichment.scopePublicId(s.scopeType(), s.scopeId()), s.id(),
                        "CANCELLED".equals(s.status()) ? "CANCELLED" : "AVAILABLE", true))
                .orElse(new ActivitySourceScheduleResponse(null, null, null, null, "UNAVAILABLE", false));
        return new ActivityDetailResponse(record,
                related.scopePublicId(), activity.getActivityEndDate(),
                activity.getVersion(), canEdit, canEdit && activity.getStatus() == ActivityStatus.DRAFT,
                canEdit, source, related.participants(), related.templateFields());
    }

    /** コメント等の別入口にはmetadata例外を渡さない。manualの既存認可は各機能に委ねる。 */
    public void requireActualForAutomatic(Long id, Long userId) {
        var activity = results.findById(id).orElseThrow(() -> new com.mannschaft.app.common.BusinessException(
                com.mannschaft.app.activity.ActivityErrorCode.ACTIVITY_NOT_FOUND));
        if (activity.isAutoGeneratedFromSchedule()) {
            requireAutomaticAccess(activity, userId, false);
            activityService.getActivity(id, userId);
        }
    }

    /** 保存済みactualの編集者例外と、一般読者の恒久source ACLを全auto読取入口で共有する。 */
    private java.util.Optional<com.mannschaft.app.schedule.dto.ScheduleActivitySource> requireAutomaticAccess(
            ActivityResultEntity activity, Long userId, boolean allowMetadata) {
        scopeAccessGuard.checkMembership(userId, activity.getScopeType(), activity.getScopeId());
        boolean editor = Objects.equals(activity.getCreatedBy(), userId)
                || scopeAccessGuard.isAdminOrAbove(userId, activity.getScopeType(), activity.getScopeId());
        if (editor) return java.util.Optional.empty();
        var source = activity.getScheduleId() == null
                ? java.util.Optional.<com.mannschaft.app.schedule.dto.ScheduleActivitySource>empty()
                : scheduleSources.visibleSource(activity.getScheduleId(), userId)
                .filter(s -> activity.getScopeType().name().equals(s.scopeType()) && Objects.equals(activity.getScopeId(), s.scopeId()));
        if (source.isEmpty() || (!allowMetadata && activity.getStatus() == ActivityStatus.DRAFT)) {
            throw new com.mannschaft.app.common.BusinessException(com.mannschaft.app.activity.ActivityErrorCode.ACTIVITY_NOT_FOUND);
        }
        return source;
    }

    /** URLのactivityIdではなく、保存コメントの実際の親でauto actualを検証する。 */
    public void requireActualForComment(Long commentId, Long userId) {
        var comment = comments.findById(commentId).orElseThrow(() -> new com.mannschaft.app.common.BusinessException(
                com.mannschaft.app.activity.ActivityErrorCode.COMMENT_NOT_FOUND));
        requireActualForAutomatic(comment.getActivityResultId(), userId);
    }

    public com.mannschaft.app.activity.dto.ActivityDeletionReference deletionReference(Long id, Long userId) {
        var activity = results.findById(id).orElseThrow(() -> new com.mannschaft.app.common.BusinessException(
                com.mannschaft.app.activity.ActivityErrorCode.ACTIVITY_NOT_FOUND));
        if (activity.isAutoGeneratedFromSchedule()) {
            scopeAccessGuard.checkMembership(userId, activity.getScopeType(), activity.getScopeId());
        }
        scopeAccessGuard.checkAuthorOrAdmin(userId, activity.getCreatedBy(), activity.getScopeType(), activity.getScopeId());
        return new com.mannschaft.app.activity.dto.ActivityDeletionReference(activity.getId(),
                activity.getScopeType().name(), activity.getScopeId(), activity.getScheduleId(),
                activity.isAutoGeneratedFromSchedule(), activity.getVersion());
    }

    /** metadata専用投影。actual writer/read guardには渡さず、現在の認可済み予定だけを表示する。 */
    private ActivityDetailResponse metadataDetail(ActivityResultEntity activity,
            com.mannschaft.app.schedule.dto.ScheduleActivitySource source) {
        var values = ActivityScheduleValues.from(source);
        var record = mapper.toActivityRecordResponse(activity).toBuilder().metadataOnly(true)
                .title(values.title()).activityDate(values.activityDate())
                .activityTimeStart(values.activityTimeStart()).activityTimeEnd(values.activityTimeEnd())
                .description(null).fieldValues(null).attachments(null).templateId(null).createdBy(null)
                .location(null).venueId(null).createdAt(null).updatedAt(null).build();
        var scopePublicId = enrichment.scopePublicId(source.scopeType(), source.scopeId());
        return new ActivityDetailResponse(record, scopePublicId, values.activityEndDate(), null,
                false, false, false, new ActivitySourceScheduleResponse(source.scopeType(), source.scopeId(),
                scopePublicId, source.id(), "CANCELLED".equals(source.status()) ? "CANCELLED" : "AVAILABLE", true),
                List.of(), List.of());
    }
}
