package com.mannschaft.app.activity.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mannschaft.app.activity.ActivityScopeType;
import com.mannschaft.app.activity.ActivityStatus;
import com.mannschaft.app.activity.entity.ActivityResultEntity;
import com.mannschaft.app.activity.repository.ActivityResultRepository;
import com.mannschaft.app.schedule.dto.ScheduleActivitySource;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Objects;
import java.util.Set;

/** 認可済み予定保存に付随する純activity writer。出欠・公開・実績本文を生成しない。 */
@Service
@RequiredArgsConstructor
public class AutomaticScheduleActivityService {
    private final ActivityResultRepository results;
    private final ObjectMapper json;

    @Transactional
    public void createAutomatic(ScheduleActivitySource source, Long createdBy) {
        if (!"TEAM".equals(source.scopeType()) && !"ORGANIZATION".equals(source.scopeType())) return;
        ActivityScopeType type = ActivityScopeType.valueOf(source.scopeType());
        boolean existing = results.lockScheduleLinksIn(java.util.List.of(source.id())).stream()
                .anyMatch(a -> a.getScopeType() == type && Objects.equals(a.getScopeId(), source.scopeId()));
        if (existing || !results.lockAutomaticHistoryIds(type.name(), source.scopeId(), source.id()).isEmpty()) return;
        ActivityScheduleValues values = ActivityScheduleValues.from(source);
        results.saveAndFlush(ActivityResultEntity.builder().scopeType(type).scopeId(source.scopeId())
                .scheduleId(source.id()).createdBy(createdBy).status(ActivityStatus.DRAFT)
                .autoGeneratedFromSchedule(true).planned(true).title(values.title())
                .activityDate(values.activityDate()).activityEndDate(values.activityEndDate())
                .activityTimeStart(values.activityTimeStart()).activityTimeEnd(values.activityTimeEnd())
                .scheduleSyncState(snapshot(values)).build());
    }

    private String snapshot(ActivityScheduleValues values) {
        try {
            return json.writeValueAsString(new ActivityScheduleSyncState(values, Set.of()));
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("自動活動の予定基準値を保存できません", e);
        }
    }
}
