package com.mannschaft.app.activity.service;

import com.mannschaft.app.activity.ActivityMapper;
import com.mannschaft.app.activity.ActivityScopeType;
import com.mannschaft.app.activity.ActivityStatus;
import com.mannschaft.app.activity.dto.ActivityRecordResponse;
import com.mannschaft.app.activity.repository.ActivityResultRepository;
import com.mannschaft.app.common.visibility.MembershipBatchQueryService;
import com.mannschaft.app.common.visibility.ScopeKey;
import com.mannschaft.app.common.visibility.mapping.ActivityVisibilityMapper;
import com.mannschaft.app.schedule.service.ScheduleActivityVisibilityService;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

/** 非TXの読取段取り役。予定ACLのbulk判定後、同一述語でページと総件数を取得する。 */
@Service
@RequiredArgsConstructor
public class AutomaticActivityListService {
    private final ActivityResultRepository results;
    private final ActivityScopeAccessGuard access;
    private final MembershipBatchQueryService memberships;
    private final ScheduleActivityVisibilityService sources;
    private final ActivityMapper mapper;

    /** 統計/CSVはmetadataを含めず、公開済み可視actualまたは所属編集者のautoだけを数える。 */
    public Set<Long> actualIds(Long userId, ActivityScopeType type, Long scopeId) {
        var references = results.findAutomaticReferences(type, scopeId);
        if (references.isEmpty()) return Set.of();
        boolean member = userId != null && access.isMember(userId, type, scopeId);
        boolean admin = member && access.isAdminOrAbove(userId, type, scopeId);
        var scope = new ScopeKey(type.name(), scopeId);
        var roles = memberships.snapshotForUser(userId, Set.of(scope), Set.of(scope));
        var levels = ActivityVisibilityMapper.toFunctional(memberships.resolveVisibleLevels(scope, roles));
        var visibleSources = sources.visibleSources(references.stream().map(r -> r.scheduleId())
                .filter(Objects::nonNull).collect(Collectors.toSet()), userId);
        return references.stream().filter(r -> {
            if (member && (admin || Objects.equals(r.createdBy(), userId))) return true;
            if (r.status() != ActivityStatus.PUBLISHED || !levels.contains(r.visibility())) return false;
            var source = visibleSources.get(r.scheduleId());
            return source != null && Objects.equals(r.scopeType(), source.scopeType())
                    && Objects.equals(r.scopeId(), source.scopeId());
        }).map(r -> r.id()).collect(Collectors.toSet());
    }

    /** 元予定の閲覧認可済みlinked入口へ、未公開actualを含まないauto行だけ追加する。 */
    public java.util.List<ActivityRecordResponse> linkedMetadata(com.mannschaft.app.schedule.dto.ScheduleActivitySource source,
                                                                Long userId) {
        var type = ActivityScopeType.valueOf(source.scopeType());
        if (!access.isMember(userId, type, source.scopeId())) return java.util.List.of();
        boolean admin = access.isAdminOrAbove(userId, type, source.scopeId());
        var values = ActivityScheduleValues.from(source);
        return results.findAllByScheduleIdOrderByIdAsc(source.id()).stream()
                .filter(a -> a.getScopeType() == type && Objects.equals(a.getScopeId(), source.scopeId()))
                .filter(a -> a.isAutoGeneratedFromSchedule() && a.getStatus() == ActivityStatus.DRAFT)
                .filter(a -> !admin && !Objects.equals(a.getCreatedBy(), userId))
                .map(a -> mapper.toActivityRecordResponse(a).toBuilder().metadataOnly(true)
                        .title(values.title()).activityDate(values.activityDate())
                        .activityTimeStart(values.activityTimeStart()).activityTimeEnd(values.activityTimeEnd())
                        .templateId(null).description(null).fieldValues(null).attachments(null).createdBy(null)
                        .location(null).venueId(null).createdAt(null).updatedAt(null).build()).toList();
    }

    public Page<ActivityRecordResponse> list(Long userId, ActivityScopeType scopeType, Long scopeId,
                                             Long templateId, Pageable pageable) {
        access.checkMembership(userId, scopeType, scopeId);
        var scope = new ScopeKey(scopeType.name(), scopeId);
        var roles = memberships.snapshotForUser(userId, Set.of(scope), Set.of(scope));
        var levels = ActivityVisibilityMapper.toFunctional(memberships.resolveVisibleLevels(scope, roles));
        boolean admin = access.isAdminOrAbove(userId, scopeType, scopeId);
        var references = results.findAutomaticReferences(scopeType, scopeId);
        var visibleSources = sources.visibleSources(references.stream().map(r -> r.scheduleId())
                .filter(Objects::nonNull).collect(Collectors.toSet()), userId);
        Set<Long> editors = references.stream().filter(r -> admin || Objects.equals(r.createdBy(), userId))
                .map(r -> r.id()).collect(Collectors.toSet());
        Set<Long> allowed = references.stream().filter(r -> {
            if (editors.contains(r.id())) return true;
            var source = visibleSources.get(r.scheduleId());
            return source != null && Objects.equals(r.scopeType(), source.scopeType())
                    && Objects.equals(r.scopeId(), source.scopeId()) && levels.contains(r.visibility());
        }).map(r -> r.id()).collect(Collectors.toSet());
        var page = results.findVisibleWithAutomaticIds(scopeType, scopeId, templateId, levels,
                userId, roles.isSystemAdmin(), allowed.isEmpty() ? Set.of(-1L) : allowed, pageable);
        return page.map(a -> {
            var raw = mapper.toActivityRecordResponse(a);
            if (!a.isAutoGeneratedFromSchedule() || a.getStatus() != ActivityStatus.DRAFT || editors.contains(a.getId())) {
                return raw;
            }
            var source = visibleSources.get(a.getScheduleId());
            var values = ActivityScheduleValues.from(source);
            return raw.toBuilder().metadataOnly(true).title(values.title()).activityDate(values.activityDate())
                    .activityTimeStart(values.activityTimeStart()).activityTimeEnd(values.activityTimeEnd())
                    .templateId(null).description(null).fieldValues(null).attachments(null).createdBy(null)
                    .location(null).venueId(null).createdAt(null).updatedAt(null).build();
        });
    }
}
