package com.mannschaft.app.activity.dto;

/** 認可した保存活動の削除参照。本文/結果/添付を共通writerへ渡さない。 */
public record ActivityDeletionReference(Long id, String scopeType, Long scopeId, Long scheduleId,
                                        boolean autoGeneratedFromSchedule, Long version) {}
