CREATE TABLE analytics_daily_users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    date DATE NOT NULL,
    new_users INT UNSIGNED NOT NULL DEFAULT 0,
    active_users INT UNSIGNED NOT NULL DEFAULT 0,
    paying_users INT UNSIGNED NOT NULL DEFAULT 0,
    churned_users INT UNSIGNED NOT NULL DEFAULT 0,
    reactivated_users INT UNSIGNED NOT NULL DEFAULT 0,
    total_users INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_date (date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
