CREATE TABLE analytics_funnel_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    date DATE NOT NULL,
    stage ENUM('REGISTERED', 'TEAM_JOINED', 'MODULE_ACTIVATED', 'FIRST_PAYMENT', 'SUBSCRIBED', 'RETAINED_3M', 'RETAINED_6M', 'RETAINED_12M') NOT NULL,
    user_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_date_stage (date, stage)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
