CREATE TABLE ad_invoices (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    advertiser_account_id BIGINT UNSIGNED NOT NULL,
    invoice_number VARCHAR(20) NOT NULL,
    invoice_month DATE NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_rate DECIMAL(5,2) NOT NULL DEFAULT 10.00,
    tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_with_tax DECIMAL(12,2) NOT NULL DEFAULT 0,
    status ENUM('DRAFT','ISSUED','PAID','OVERDUE') NOT NULL DEFAULT 'DRAFT',
    stripe_invoice_id VARCHAR(50),
    issued_at DATETIME,
    paid_at DATETIME,
    due_date DATE,
    note VARCHAR(500),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_account_month (advertiser_account_id, invoice_month),
    UNIQUE KEY uk_invoice_number (invoice_number),
    INDEX idx_status_due (status, due_date),
    INDEX idx_account_status (advertiser_account_id, status),
    CONSTRAINT fk_ad_invoices_account FOREIGN KEY (advertiser_account_id) REFERENCES advertiser_accounts(id),
    CONSTRAINT chk_invoice_month_first CHECK (DAY(invoice_month) = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
