CREATE TABLE onboarding_progresses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    template_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    scope_type VARCHAR(20) NOT NULL,
    scope_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    total_steps SMALLINT NOT NULL,
    completed_steps SMALLINT NOT NULL DEFAULT 0,
    deadline_at DATETIME DEFAULT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME DEFAULT NULL,
    last_reminded_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_op_template_user (template_id, user_id),
    INDEX idx_op_scope (scope_type, scope_id, status),
    INDEX idx_op_user (user_id, status),
    INDEX idx_op_deadline (status, deadline_at),
    INDEX idx_op_scope_completed (scope_type, scope_id, completed_at DESC),
    CONSTRAINT chk_op_scope_type CHECK (scope_type IN ('TEAM', 'ORGANIZATION')),
    CONSTRAINT chk_op_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'SKIPPED')),
    CONSTRAINT fk_op_template FOREIGN KEY (template_id) REFERENCES onboarding_templates(id) ON DELETE RESTRICT,
    CONSTRAINT fk_op_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
