CREATE TABLE member_skills (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    skill_category_id BIGINT UNSIGNED DEFAULT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    scope_type VARCHAR(50) NOT NULL,
    scope_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    issuer VARCHAR(200) DEFAULT NULL,
    credential_number VARCHAR(100) DEFAULT NULL,
    acquired_on DATE DEFAULT NULL,
    expires_at DATE DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING_REVIEW',
    certificate_s3_key VARCHAR(500) DEFAULT NULL,
    verified_at DATETIME DEFAULT NULL,
    verified_by BIGINT UNSIGNED DEFAULT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_ms_user_scope (user_id, scope_type, scope_id),
    INDEX idx_ms_expires_at (expires_at, status),
    INDEX idx_ms_skill_category (skill_category_id),
    CONSTRAINT chk_ms_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'PENDING_REVIEW')),
    CONSTRAINT fk_ms_skill_category FOREIGN KEY (skill_category_id) REFERENCES skill_categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_ms_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ms_verified_by FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
