CREATE TABLE budget_transactions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    fiscal_year_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NOT NULL,
    scope_type VARCHAR(20) NOT NULL,
    scope_id BIGINT UNSIGNED NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount DECIMAL(12,0) NOT NULL,
    transaction_date DATE NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT DEFAULT NULL,
    payment_method VARCHAR(30) DEFAULT NULL,
    reference_number VARCHAR(100) DEFAULT NULL,
    counterparty VARCHAR(200) DEFAULT NULL,
    is_auto_recorded BOOLEAN NOT NULL DEFAULT FALSE,
    source_type VARCHAR(50) DEFAULT NULL,
    source_id BIGINT UNSIGNED DEFAULT NULL,
    reversal_of_id BIGINT UNSIGNED DEFAULT NULL,
    workflow_request_id BIGINT UNSIGNED DEFAULT NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
    recorded_by BIGINT UNSIGNED NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_bt_fiscal_year (fiscal_year_id),
    INDEX idx_bt_category (category_id),
    INDEX idx_bt_scope (scope_type, scope_id),
    INDEX idx_bt_transaction_date (transaction_date),
    INDEX idx_bt_approval_status (approval_status),
    INDEX idx_bt_source (source_type, source_id),
    INDEX idx_bt_recorded_by (recorded_by),
    CONSTRAINT chk_bt_transaction_type CHECK (transaction_type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT chk_bt_approval_status CHECK (approval_status IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    CONSTRAINT chk_bt_scope_type CHECK (scope_type IN ('TEAM', 'ORGANIZATION')),
    CONSTRAINT fk_bt_fiscal_year FOREIGN KEY (fiscal_year_id) REFERENCES budget_fiscal_years(id) ON DELETE RESTRICT,
    CONSTRAINT fk_bt_category FOREIGN KEY (category_id) REFERENCES budget_categories(id) ON DELETE RESTRICT,
    CONSTRAINT fk_bt_reversal_of FOREIGN KEY (reversal_of_id) REFERENCES budget_transactions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_bt_workflow_request FOREIGN KEY (workflow_request_id) REFERENCES workflow_requests(id) ON DELETE SET NULL,
    CONSTRAINT fk_bt_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
