CREATE TABLE kb_pages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scope_type VARCHAR(50) NOT NULL,
    scope_id BIGINT UNSIGNED NOT NULL,
    parent_id BIGINT UNSIGNED DEFAULT NULL COMMENT '自己参照（ルートページはNULL）',
    path VARCHAR(1000) NOT NULL COMMENT 'マテリアライズドパス /1/5/12形式',
    depth INT NOT NULL DEFAULT 0,
    title VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    body MEDIUMTEXT DEFAULT NULL,
    icon VARCHAR(50) DEFAULT NULL,
    access_level VARCHAR(30) NOT NULL DEFAULT 'ALL_MEMBERS',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    view_count INT NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NOT NULL,
    last_edited_by BIGINT UNSIGNED DEFAULT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_kbp_scope (scope_type, scope_id),
    INDEX idx_kbp_path (scope_type, scope_id, path(200)),
    INDEX idx_kbp_slug (scope_type, scope_id, slug),
    FULLTEXT INDEX ft_kbp_search (title, body) WITH PARSER ngram,
    CONSTRAINT fk_kbp_parent FOREIGN KEY (parent_id) REFERENCES kb_pages(id) ON DELETE RESTRICT,
    CONSTRAINT fk_kbp_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_kbp_last_edited_by FOREIGN KEY (last_edited_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
