CREATE TABLE budget_reports (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    fiscal_year_id BIGINT UNSIGNED NOT NULL,
    scope_type VARCHAR(20) NOT NULL,
    scope_id BIGINT UNSIGNED NOT NULL,
    report_type VARCHAR(20) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    file_key VARCHAR(500) DEFAULT NULL,
    file_size INT UNSIGNED DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'GENERATING',
    generated_by BIGINT UNSIGNED NOT NULL,
    generated_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_br_fiscal_year (fiscal_year_id),
    INDEX idx_br_scope (scope_type, scope_id),
    INDEX idx_br_generated_by (generated_by),
    CONSTRAINT chk_br_report_type CHECK (report_type IN ('MONTHLY', 'ANNUAL')),
    CONSTRAINT chk_br_status CHECK (status IN ('GENERATING', 'COMPLETED', 'FAILED')),
    CONSTRAINT fk_br_fiscal_year FOREIGN KEY (fiscal_year_id) REFERENCES budget_fiscal_years(id) ON DELETE RESTRICT,
    CONSTRAINT fk_br_generated_by FOREIGN KEY (generated_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
