CREATE TABLE kb_templates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scope_type VARCHAR(50) NOT NULL,
    scope_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'SYSTEMの場合NULL',
    name VARCHAR(100) NOT NULL,
    body MEDIUMTEXT DEFAULT NULL,
    icon VARCHAR(50) DEFAULT NULL,
    is_system TINYINT(1) NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_kbt_scope (scope_type, scope_id),
    CONSTRAINT fk_kbt_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
