-- F04.9: 確認通知本体テーブル
CREATE TABLE confirmable_notifications (
    id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_type           VARCHAR(40) NOT NULL DEFAULT 'EMERGENCY_CLOSURE' COMMENT '通知発生元種別',
    scope_type            ENUM('TEAM', 'ORGANIZATION') NOT NULL,
    scope_id              BIGINT UNSIGNED NOT NULL,
    title                 VARCHAR(200) NOT NULL,
    body                  TEXT NULL,
    priority              ENUM('NORMAL', 'HIGH', 'URGENT') NOT NULL DEFAULT 'NORMAL',
    status                ENUM('ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE',
    deadline_at           DATETIME NULL       COMMENT '確認期限。NULLは無期限',
    first_reminder_minutes  INT NULL          COMMENT '1回目リマインド（分）。NULLはスコープ設定を継承',
    second_reminder_minutes INT NULL          COMMENT '2回目リマインド（分）。NULLはスコープ設定を継承',
    action_url            VARCHAR(500) NULL   COMMENT '確認ボタン遷移先URL',
    cancelled_at          DATETIME NULL,
    cancelled_by          BIGINT UNSIGNED NULL,
    completed_at          DATETIME NULL,
    expired_at            DATETIME NULL,
    total_recipient_count INT NOT NULL DEFAULT 0 COMMENT '送信先人数（受信者追加時に更新）',
    template_id           BIGINT UNSIGNED NULL COMMENT '使用したテンプレートID（参照用）',
    created_by            BIGINT UNSIGNED NULL,
    created_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_cn_source_status (source_type, status),
    INDEX idx_cn_scope    (scope_type, scope_id, created_at DESC),
    INDEX idx_cn_status   (status, created_at DESC),
    INDEX idx_cn_deadline (status, deadline_at),
    INDEX idx_cn_created_by (created_by),
    CONSTRAINT fk_cn_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cn_created_by   FOREIGN KEY (created_by)   REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='確認通知';
