-- F13.1 Phase 13.1.1 MVP: 求人投稿テーブル
-- MVP 範囲のカラムのみ定義。QR/TODO/エスクロー/手数料関連カラムは Phase 13.1.2-7 の ALTER で追加する。
CREATE TABLE job_postings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  team_id BIGINT UNSIGNED NOT NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(50) NULL,
  work_location_type ENUM('ONSITE','ONLINE','HYBRID') NOT NULL DEFAULT 'ONSITE',
  work_address VARCHAR(255) NULL,
  work_start_at DATETIME NOT NULL,
  work_end_at DATETIME NOT NULL,
  reward_type ENUM('HOURLY','DAILY','LUMP_SUM') NOT NULL DEFAULT 'LUMP_SUM',
  base_reward_jpy INT NOT NULL,
  capacity INT NOT NULL DEFAULT 1,
  application_deadline_at DATETIME NOT NULL,
  visibility_scope ENUM('TEAM_MEMBERS','TEAM_MEMBERS_SUPPORTERS','JOBBER_INTERNAL','JOBBER_PUBLIC_BOARD','ORGANIZATION_SCOPE','CUSTOM_TEMPLATE') NOT NULL DEFAULT 'TEAM_MEMBERS',
  status ENUM('DRAFT','OPEN','CLOSED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  publish_at DATETIME NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  CONSTRAINT fk_jp_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE,
  CONSTRAINT fk_jp_creator FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT chk_reward_min CHECK (base_reward_jpy >= 500),
  CONSTRAINT chk_reward_max CHECK (base_reward_jpy <= 1000000),
  CONSTRAINT chk_capacity_positive CHECK (capacity >= 1),
  CONSTRAINT chk_work_time CHECK (work_end_at > work_start_at),
  CONSTRAINT chk_deadline CHECK (application_deadline_at <= work_start_at),
  INDEX idx_jp_team_status (team_id, status, deleted_at),
  INDEX idx_jp_status_deadline (status, application_deadline_at),
  INDEX idx_jp_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='F13.1 MVP: 求人投稿';
