CREATE TABLE event_rsvp_responses (
  id           BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_id     BIGINT UNSIGNED NOT NULL,
  user_id      BIGINT UNSIGNED NOT NULL,
  response     VARCHAR(20)     NOT NULL DEFAULT 'UNDECIDED'
               COMMENT 'ATTENDING / NOT_ATTENDING / MAYBE / UNDECIDED',
  comment      VARCHAR(500),
  responded_at DATETIME,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_rsvp_event_user (event_id, user_id),
  CONSTRAINT fk_rsvp_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  CONSTRAINT fk_rsvp_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
