-- F03.12 ケア対象者見守り通知: アカウントレベルのケアリンクテーブル
CREATE TABLE user_care_links (
    id                         BIGINT UNSIGNED    NOT NULL AUTO_INCREMENT,
    care_recipient_user_id     BIGINT UNSIGNED    NOT NULL COMMENT 'FK → users.id（ケア対象本人）',
    watcher_user_id            BIGINT UNSIGNED    NOT NULL COMMENT 'FK → users.id（見守り者）',
    care_category              ENUM('MINOR','ELDERLY','DISABILITY_SUPPORT','GENERAL_FAMILY') NOT NULL COMMENT 'このリンクのケア区分',
    relationship               ENUM('PARENT','CHILD','SPOUSE','GRANDPARENT','GRANDCHILD','SIBLING','LEGAL_GUARDIAN','CARETAKER','OTHER') NOT NULL DEFAULT 'PARENT' COMMENT '続柄',
    is_primary                 BOOLEAN            NOT NULL DEFAULT TRUE COMMENT '主見守り者フラグ（緊急時優先順）',
    status                     ENUM('PENDING','ACTIVE','REJECTED','REVOKED') NOT NULL DEFAULT 'PENDING' COMMENT 'リンク状態',
    invited_by                 ENUM('CARE_RECIPIENT','WATCHER','ADMIN','SYSTEM') NOT NULL COMMENT '招待元',
    invitation_token           VARCHAR(64)        NULL COMMENT '承認用トークン（メール招待時）',
    invitation_sent_at         DATETIME           NULL COMMENT '招待送信日時',
    confirmed_at               DATETIME           NULL COMMENT '承認日時（status=ACTIVE になった時刻）',
    notify_on_rsvp             BOOLEAN            NOT NULL DEFAULT TRUE COMMENT 'RSVP確認時通知',
    notify_on_checkin          BOOLEAN            NOT NULL DEFAULT TRUE COMMENT 'チェックイン時通知',
    notify_on_checkout         BOOLEAN            NOT NULL DEFAULT FALSE COMMENT 'チェックアウト時通知',
    notify_on_absent_alert     BOOLEAN            NOT NULL DEFAULT TRUE COMMENT '不在アラート通知',
    notify_on_dismissal        BOOLEAN            NOT NULL DEFAULT TRUE COMMENT '解散通知',
    created_by                 BIGINT UNSIGNED    NOT NULL COMMENT 'FK → users.id（作成者）',
    created_at                 DATETIME           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME           NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    revoked_at                 DATETIME           NULL COMMENT '解除日時',
    revoked_by                 BIGINT UNSIGNED    NULL COMMENT '解除実行者 users.id',

    PRIMARY KEY (id),
    CONSTRAINT uq_ucl UNIQUE (care_recipient_user_id, watcher_user_id),
    CONSTRAINT fk_ucl_recipient  FOREIGN KEY (care_recipient_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ucl_watcher    FOREIGN KEY (watcher_user_id)        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ucl_created_by FOREIGN KEY (created_by)             REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ucl_revoked_by FOREIGN KEY (revoked_by)             REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_ucl_recipient_status   (care_recipient_user_id, status),
    INDEX idx_ucl_watcher_status     (watcher_user_id, status),
    INDEX idx_ucl_invitation_token   (invitation_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='アカウントレベルのケアリンク（見守り者↔ケア対象者の関係）';
