-- 日次出欠・時限別出欠テーブルに登校場所カラムを追加する

ALTER TABLE daily_attendance_records
  ADD COLUMN attendance_location ENUM('CLASSROOM','SICK_BAY','SEPARATE_ROOM','LIBRARY','ONLINE','HOME_LEARNING','OUT_OF_SCHOOL','NOT_APPLICABLE') NOT NULL DEFAULT 'CLASSROOM' AFTER status,
  ADD COLUMN location_changed_during_day BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE period_attendance_records
  ADD COLUMN attendance_location ENUM('CLASSROOM','SICK_BAY','SEPARATE_ROOM','LIBRARY','ONLINE','HOME_LEARNING','OUT_OF_SCHOOL','NOT_APPLICABLE') NOT NULL DEFAULT 'CLASSROOM' AFTER status;
