CREATE TABLE IF NOT EXISTS student_attendance_summaries (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  team_id BIGINT NOT NULL COMMENT 'チームID',
  student_user_id BIGINT NOT NULL COMMENT '生徒ユーザーID',
  term_id BIGINT NULL COMMENT 'NULLなら年度通算',
  academic_year SMALLINT NOT NULL COMMENT '学年度（例: 2025）',
  period_from DATE NOT NULL COMMENT '集計期間開始（転入生対応）',
  period_to DATE NOT NULL COMMENT '集計期間終了',
  total_school_days SMALLINT NOT NULL DEFAULT 0 COMMENT '授業日数',
  present_days SMALLINT NOT NULL DEFAULT 0 COMMENT '出席日数',
  absent_days SMALLINT NOT NULL DEFAULT 0 COMMENT '欠席日数',
  late_count SMALLINT NOT NULL DEFAULT 0 COMMENT '遅刻回数',
  early_leave_count SMALLINT NOT NULL DEFAULT 0 COMMENT '早退回数',
  official_absence_days SMALLINT NOT NULL DEFAULT 0 COMMENT '公欠日数',
  school_activity_days SMALLINT NOT NULL DEFAULT 0 COMMENT '学校行事日数',
  sick_bay_days SMALLINT NOT NULL DEFAULT 0 COMMENT '保健室登校日数',
  separate_room_days SMALLINT NOT NULL DEFAULT 0 COMMENT '別室登校日数',
  online_days SMALLINT NOT NULL DEFAULT 0 COMMENT 'オンライン登校日数',
  home_learning_days SMALLINT NOT NULL DEFAULT 0 COMMENT '家庭学習日数',
  attendance_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '出席率（%）',
  total_periods SMALLINT NOT NULL DEFAULT 0 COMMENT '総時限数',
  present_periods SMALLINT NOT NULL DEFAULT 0 COMMENT '出席時限数',
  period_attendance_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '時限別出席率（%）',
  subject_breakdown JSON NULL COMMENT '教科別出席 {math:{present:40,absent:2,rate:95.2},...}',
  last_recalculated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終再集計日時',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_summary_student_term (student_user_id, team_id, academic_year, term_id),
  INDEX idx_summary_team_year (team_id, academic_year),
  INDEX idx_summary_student_year (student_user_id, academic_year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学期/年度別出席集計';
