-- モジュール定義シードデータ（デフォルト28個 + 選択式11個 = 39件）
INSERT INTO module_definitions (name, slug, description, module_type, module_number, requires_paid_plan, trial_days, is_active, created_at, updated_at) VALUES
-- DEFAULT モジュール（28個）
('ダッシュボード', 'dashboard', '組織・チーム・個人のダッシュボード', 'DEFAULT', 1, 0, 0, 1, NOW(), NOW()),
('TODO', 'todo', 'タスク管理機能', 'DEFAULT', 2, 0, 0, 1, NOW(), NOW()),
('タイムライン', 'timeline', 'アクティビティタイムライン', 'DEFAULT', 3, 0, 0, 1, NOW(), NOW()),
('メッセージング', 'messaging', 'ダイレクトメッセージ', 'DEFAULT', 4, 0, 0, 1, NOW(), NOW()),
('チャット', 'chat', 'グループチャット', 'DEFAULT', 5, 0, 0, 1, NOW(), NOW()),
('プッシュ通知', 'push_notification', 'プッシュ通知配信', 'DEFAULT', 6, 0, 0, 1, NOW(), NOW()),
('アンケート', 'survey', 'アンケート作成・回収', 'DEFAULT', 7, 0, 0, 1, NOW(), NOW()),
('ファイル共有', 'file_sharing', 'ファイルアップロード・共有', 'DEFAULT', 8, 0, 0, 1, NOW(), NOW()),
('検索', 'search', '横断検索機能', 'DEFAULT', 9, 0, 0, 1, NOW(), NOW()),
('モデレーション', 'moderation', 'コンテンツモデレーション', 'DEFAULT', 10, 0, 0, 1, NOW(), NOW()),
('メンション', 'mention', '@メンション通知', 'DEFAULT', 11, 0, 0, 1, NOW(), NOW()),
('監査ログ', 'audit_log', '操作履歴記録', 'DEFAULT', 12, 0, 0, 1, NOW(), NOW()),
('データエクスポート', 'data_export', 'CSV/PDFエクスポート', 'DEFAULT', 13, 0, 0, 1, NOW(), NOW()),
('多言語対応', 'i18n', '多言語インターフェース', 'DEFAULT', 14, 0, 0, 1, NOW(), NOW()),
('スケジュール', 'schedule', 'スケジュール・出欠管理', 'DEFAULT', 15, 0, 0, 1, NOW(), NOW()),
('活動記録', 'activity_record', '活動記録・レポート', 'DEFAULT', 16, 0, 0, 1, NOW(), NOW()),
('掲示板', 'bulletin', 'お知らせ・掲示板', 'DEFAULT', 17, 0, 0, 1, NOW(), NOW()),
('マッチング', 'matching', '対戦・マッチング管理', 'DEFAULT', 18, 0, 0, 1, NOW(), NOW()),
('成績管理', 'performance', '成績・実績管理', 'DEFAULT', 19, 0, 0, 1, NOW(), NOW()),
('メンバー紹介', 'member_intro', 'メンバープロフィール紹介', 'DEFAULT', 20, 0, 0, 1, NOW(), NOW()),
('回覧板', 'circular', '回覧板・既読管理', 'DEFAULT', 21, 0, 0, 1, NOW(), NOW()),
('電子印鑑', 'digital_seal', '電子承認・押印', 'DEFAULT', 22, 0, 0, 1, NOW(), NOW()),
('安否確認', 'safety_check', '災害時安否確認', 'DEFAULT', 23, 0, 0, 1, NOW(), NOW()),
('分析', 'analytics', '利用統計・分析', 'DEFAULT', 24, 0, 0, 1, NOW(), NOW()),
('テーマ', 'theme', 'UIテーマカスタマイズ', 'DEFAULT', 25, 0, 0, 1, NOW(), NOW()),
('ダイレクトメール', 'direct_mail', '一斉メール配信', 'DEFAULT', 26, 0, 0, 1, NOW(), NOW()),
('広告表示', 'ad_display', '広告枠管理・表示', 'DEFAULT', 27, 0, 0, 1, NOW(), NOW()),
('コルクボード', 'corkboard', 'コルクボード（自由掲示）', 'DEFAULT', 28, 0, 0, 1, NOW(), NOW()),
-- OPTIONAL モジュール（11個）
('QR会員証', 'qr_membership', 'QRコード会員証発行', 'OPTIONAL', 29, 0, 14, 1, NOW(), NOW()),
('決済', 'payment', 'オンライン決済・集金', 'OPTIONAL', 30, 0, 14, 1, NOW(), NOW()),
('予約管理', 'reservation', '施設・サービス予約', 'OPTIONAL', 31, 0, 14, 1, NOW(), NOW()),
('サービス記録', 'service_record', '施術・サービス履歴管理', 'OPTIONAL', 32, 0, 14, 1, NOW(), NOW()),
('備品管理', 'equipment', '備品・設備管理', 'OPTIONAL', 33, 0, 14, 1, NOW(), NOW()),
('ギャラリー', 'gallery', '写真・動画ギャラリー', 'OPTIONAL', 34, 0, 14, 1, NOW(), NOW()),
('シフト管理', 'shift', 'シフト作成・管理', 'OPTIONAL', 35, 0, 14, 1, NOW(), NOW()),
('投票', 'voting', '投票・アンケート集計', 'OPTIONAL', 36, 0, 14, 1, NOW(), NOW()),
('住民台帳', 'resident_register', '住民・会員台帳管理', 'OPTIONAL', 37, 0, 14, 1, NOW(), NOW()),
('駐車場管理', 'parking', '駐車場割当・管理', 'OPTIONAL', 38, 0, 14, 1, NOW(), NOW()),
('カルテ管理', 'medical_record', '医療・施術カルテ', 'OPTIONAL', 39, 1, 14, 1, NOW(), NOW());
