CREATE TABLE queue_tickets (
    id                      BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    category_id             BIGINT UNSIGNED  NOT NULL,
    counter_id              BIGINT UNSIGNED  NOT NULL,
    ticket_number           VARCHAR(20)      NOT NULL,
    user_id                 BIGINT UNSIGNED,
    guest_name              VARCHAR(50),
    party_size              SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    source                  VARCHAR(10)      NOT NULL,
    status                  VARCHAR(20)      NOT NULL DEFAULT 'WAITING',
    position                INT UNSIGNED     NOT NULL,
    estimated_wait_minutes  SMALLINT UNSIGNED,
    called_at               DATETIME,
    serving_at              DATETIME,
    completed_at            DATETIME,
    cancelled_at            DATETIME,
    cancelled_by            BIGINT UNSIGNED,
    no_show_at              DATETIME,
    hold_until              DATETIME,
    hold_used               BOOLEAN          NOT NULL DEFAULT FALSE,
    actual_service_minutes  SMALLINT UNSIGNED,
    note                    VARCHAR(300),
    previous_ticket_id      BIGINT UNSIGNED,
    issued_date             DATE             NOT NULL,
    created_at              DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_qtkt_counter_date_status (counter_id, issued_date, status, position),
    INDEX idx_qtkt_category_date_status (category_id, issued_date, status, position),
    INDEX idx_qtkt_user_date (user_id, issued_date DESC),

    CONSTRAINT fk_qtkt_category FOREIGN KEY (category_id) REFERENCES queue_categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_qtkt_counter FOREIGN KEY (counter_id) REFERENCES queue_counters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_qtkt_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_qtkt_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_qtkt_previous FOREIGN KEY (previous_ticket_id) REFERENCES queue_tickets (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='順番待ちチケット';
