-- F02.1 QR会員証: 会員証マスターテーブル
CREATE TABLE member_cards (
    id                BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    user_id           BIGINT UNSIGNED  NOT NULL,
    scope_type        VARCHAR(20)      NOT NULL COMMENT 'スコープ種別（PLATFORM / TEAM / ORGANIZATION）',
    scope_id          BIGINT UNSIGNED  NULL     COMMENT 'FK → teams.id or organizations.id。PLATFORM の場合は NULL',
    card_code         CHAR(36)         NOT NULL COMMENT '会員証コード（UUID v4）',
    card_number       VARCHAR(20)      NOT NULL COMMENT '表示用会員番号（例: M-000001）',
    display_name      VARCHAR(100)     NOT NULL COMMENT '会員証に表示する名前',
    status            VARCHAR(20)      NOT NULL DEFAULT 'ACTIVE' COMMENT 'ステータス（ACTIVE / SUSPENDED / REVOKED）',
    issued_at         DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '発行日時',
    suspended_at      DATETIME         NULL     COMMENT '一時停止日時',
    revoked_at        DATETIME         NULL     COMMENT '無効化日時',
    last_checkin_at   DATETIME         NULL     COMMENT '最終チェックイン日時（denormalize）',
    checkin_count     INT UNSIGNED     NOT NULL DEFAULT 0 COMMENT 'チェックイン回数（denormalize）',
    total_spend       DECIMAL(12,2)    NOT NULL DEFAULT 0.00 COMMENT '累計売上額（Phase 8 で使用開始）',
    qr_secret         VARCHAR(64)      NOT NULL COMMENT 'QR署名用シークレット（HMAC-SHA256）',
    created_at        DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at        DATETIME         NULL     COMMENT '論理削除',
    active_unique_key TINYINT GENERATED ALWAYS AS (IF(deleted_at IS NULL, 1, NULL)) VIRTUAL COMMENT 'パーシャルユニーク用',
    PRIMARY KEY (id),
    UNIQUE KEY uq_mc_user_scope_active (user_id, scope_type, scope_id, active_unique_key),
    UNIQUE KEY uq_mc_card_code (card_code),
    INDEX idx_mc_scope (scope_type, scope_id, status),
    INDEX idx_mc_card_number (scope_type, scope_id, card_number),
    INDEX idx_mc_last_checkin (scope_type, scope_id, last_checkin_at DESC),
    CONSTRAINT fk_mc_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='デジタル会員証マスター';
