-- F02.3: TODOタスク本体テーブル
CREATE TABLE todos (
    id           BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    scope_type   VARCHAR(20)      NOT NULL COMMENT 'PERSONAL / TEAM / ORGANIZATION',
    scope_id     BIGINT UNSIGNED  NOT NULL COMMENT 'users.id / teams.id / organizations.id',
    project_id   BIGINT UNSIGNED  NULL,
    milestone_id BIGINT UNSIGNED  NULL,
    title        VARCHAR(300)     NOT NULL,
    description  TEXT             NULL,
    status       VARCHAR(20)      NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / IN_PROGRESS / COMPLETED',
    priority     VARCHAR(10)      NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW / MEDIUM / HIGH / URGENT',
    due_date     DATE             NULL,
    due_time     TIME             NULL,
    completed_at DATETIME         NULL,
    completed_by BIGINT UNSIGNED  NULL,
    created_by   BIGINT UNSIGNED  NOT NULL,
    sort_order   INT              NOT NULL DEFAULT 0,
    created_at   DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at   DATETIME         NULL,
    PRIMARY KEY (id),
    INDEX idx_todo_scope_status (scope_type, scope_id, status, priority, due_date),
    INDEX idx_todo_project (project_id, status, sort_order),
    INDEX idx_todo_milestone (milestone_id, status, sort_order),
    INDEX idx_todo_due_date (due_date, status),
    INDEX idx_todo_created_by (created_by),
    CONSTRAINT fk_todo_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL,
    CONSTRAINT fk_todo_milestone FOREIGN KEY (milestone_id) REFERENCES project_milestones (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
