-- F03.8 イベント管理: イベントテーブル
CREATE TABLE events (
    id                      BIGINT          NOT NULL AUTO_INCREMENT,
    scope_type              VARCHAR(20)     NOT NULL,
    scope_id                BIGINT          NOT NULL,
    schedule_id             BIGINT,
    slug                    VARCHAR(100)    NOT NULL,
    subtitle                VARCHAR(200),
    summary                 TEXT,
    cover_image_key         VARCHAR(300),
    venue_name              VARCHAR(200),
    venue_address           VARCHAR(500),
    venue_latitude          DECIMAL(10,7),
    venue_longitude         DECIMAL(10,7),
    venue_access_info       TEXT,
    status                  VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    is_public               BOOLEAN         NOT NULL DEFAULT FALSE,
    min_registration_role   VARCHAR(30)     NOT NULL DEFAULT 'MEMBER_PLUS',
    registration_starts_at  DATETIME,
    registration_ends_at    DATETIME,
    max_capacity            INT UNSIGNED,
    is_approval_required    BOOLEAN         NOT NULL DEFAULT FALSE,
    post_survey_id          BIGINT,
    workflow_request_id     BIGINT,
    ogp_title               VARCHAR(200),
    ogp_description         VARCHAR(500),
    ogp_image_key           VARCHAR(300),
    registration_count      INT UNSIGNED    NOT NULL DEFAULT 0,
    checkin_count           INT UNSIGNED    NOT NULL DEFAULT 0,
    created_by              BIGINT,
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at              DATETIME,

    PRIMARY KEY (id),
    UNIQUE KEY uq_events_slug (slug),
    UNIQUE KEY uq_events_schedule (schedule_id),
    CONSTRAINT fk_events_schedule
        FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_created_by
        FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    INDEX idx_events_scope_status (scope_type, scope_id, status, created_at DESC),
    INDEX idx_events_public_status (is_public, status, created_at DESC),
    INDEX idx_events_status_reg_end (status, registration_ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='イベント';
