CREATE TABLE recruitment_templates (
    id                              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scope_type                      ENUM('TEAM','ORGANIZATION') NOT NULL,
    scope_id                        BIGINT UNSIGNED NOT NULL,
    category_id                     BIGINT UNSIGNED NOT NULL,
    subcategory_id                  BIGINT UNSIGNED,
    template_name                   VARCHAR(100) NOT NULL,
    title                           VARCHAR(100) NOT NULL,
    description                     TEXT,
    participation_type              ENUM('INDIVIDUAL','TEAM') NOT NULL DEFAULT 'INDIVIDUAL',
    default_capacity                INT UNSIGNED NOT NULL DEFAULT 10,
    default_min_capacity            INT UNSIGNED NOT NULL DEFAULT 1,
    default_duration_minutes        INT UNSIGNED NOT NULL DEFAULT 90,
    default_application_deadline_hours INT UNSIGNED NOT NULL DEFAULT 24,
    default_auto_cancel_hours       INT UNSIGNED NOT NULL DEFAULT 24,
    default_payment_enabled         BOOLEAN NOT NULL DEFAULT FALSE,
    default_price                   INT UNSIGNED,
    default_visibility              ENUM('PUBLIC','SCOPE_ONLY','SUPPORTERS_ONLY') NOT NULL DEFAULT 'SCOPE_ONLY',
    default_location                VARCHAR(200),
    default_reservation_line_id     BIGINT UNSIGNED,
    default_image_url               VARCHAR(500),
    default_cancellation_policy_id  BIGINT UNSIGNED,
    created_by                      BIGINT UNSIGNED NOT NULL,
    created_at                      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at                      DATETIME(6),
    PRIMARY KEY (id),
    INDEX idx_rt_scope (scope_type, scope_id),
    INDEX idx_rt_scope_active (scope_type, scope_id, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='F03.11 Phase 3 募集テンプレート';
