-- F04.1 タイムライン投稿テーブル
CREATE TABLE timeline_posts (
    id              BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT,
    scope_type      VARCHAR(20)  NOT NULL,
    scope_id        BIGINT UNSIGNED       NOT NULL DEFAULT 0,
    user_id         BIGINT UNSIGNED NOT NULL,
    social_profile_id BIGINT UNSIGNED     NULL,
    posted_as_type  VARCHAR(20)  NOT NULL DEFAULT 'USER',
    posted_as_id    BIGINT UNSIGNED       NULL,
    parent_id       BIGINT UNSIGNED       NULL,
    content         TEXT         NULL,
    repost_of_id    BIGINT UNSIGNED       NULL,
    repost_count    INT          NOT NULL DEFAULT 0,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PUBLISHED',
    scheduled_at    DATETIME     NULL,
    is_pinned       BOOLEAN      NOT NULL DEFAULT FALSE,
    reaction_count  INT          NOT NULL DEFAULT 0,
    reply_count     INT          NOT NULL DEFAULT 0,
    attachment_count SMALLINT    NOT NULL DEFAULT 0,
    edit_count      SMALLINT     NOT NULL DEFAULT 0,
    deleted_at      DATETIME     NULL,
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_timeline_posts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_timeline_posts_parent FOREIGN KEY (parent_id) REFERENCES timeline_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_timeline_posts_repost FOREIGN KEY (repost_of_id) REFERENCES timeline_posts(id) ON DELETE SET NULL,
    INDEX idx_timeline_posts_scope (scope_type, scope_id, deleted_at, created_at DESC),
    INDEX idx_timeline_posts_user (user_id, deleted_at, created_at DESC),
    INDEX idx_timeline_posts_parent (parent_id),
    INDEX idx_timeline_posts_pinned (is_pinned),
    INDEX idx_timeline_posts_scheduled (status, scheduled_at),
    FULLTEXT INDEX ft_timeline_posts_content (content) WITH PARSER ngram
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
