-- F05.4 アンケート・投票: surveys テーブル
CREATE TABLE surveys (
    id                          BIGINT        NOT NULL AUTO_INCREMENT,
    scope_type                  VARCHAR(20)   NOT NULL,
    scope_id                    BIGINT        NOT NULL,
    title                       VARCHAR(200)  NOT NULL,
    description                 TEXT          NULL,
    status                      VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    is_anonymous                BOOLEAN       NOT NULL DEFAULT FALSE,
    allow_multiple_submissions  BOOLEAN       NOT NULL DEFAULT FALSE,
    results_visibility          VARCHAR(20)   NOT NULL DEFAULT 'AFTER_RESPONSE',
    distribution_mode           VARCHAR(20)   NOT NULL DEFAULT 'ALL',
    auto_post_to_timeline       BOOLEAN       NOT NULL DEFAULT FALSE,
    series_id                   VARCHAR(50)   NULL,
    remind_before_hours         JSON          NULL,
    manual_remind_count         INT           NOT NULL DEFAULT 0,
    starts_at                   DATETIME      NULL,
    expires_at                  DATETIME      NULL,
    response_count              INT           NOT NULL DEFAULT 0,
    target_count                INT           NOT NULL DEFAULT 0,
    created_by                  BIGINT        NULL,
    published_at                DATETIME      NULL,
    closed_at                   DATETIME      NULL,
    version                     BIGINT        NOT NULL DEFAULT 0,
    created_at                  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at                  DATETIME      NULL,
    PRIMARY KEY (id),
    INDEX idx_surveys_scope (scope_type, scope_id),
    INDEX idx_surveys_status (status),
    INDEX idx_surveys_created_by (created_by),
    INDEX idx_surveys_series (series_id),
    INDEX idx_surveys_expires_at (expires_at),
    CONSTRAINT fk_surveys_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
