-- F05.7 書類テンプレート・フォームビルダー: フォームテンプレートテーブル
CREATE TABLE form_templates (
    id              BIGINT          NOT NULL AUTO_INCREMENT,
    scope_type      VARCHAR(20)     NOT NULL,
    scope_id        BIGINT          NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    description     VARCHAR(500),
    icon            VARCHAR(50),
    color           VARCHAR(7),
    status          VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    requires_approval BOOLEAN       NOT NULL DEFAULT FALSE,
    workflow_template_id BIGINT     NULL,
    is_seal_on_pdf  BOOLEAN         NOT NULL DEFAULT FALSE,
    deadline        DATETIME,
    allow_edit_after_submit BOOLEAN NOT NULL DEFAULT FALSE,
    auto_fill_enabled BOOLEAN       NOT NULL DEFAULT FALSE,
    max_submissions_per_user INT    NOT NULL DEFAULT 0,
    sort_order      INT             NOT NULL DEFAULT 0,
    preset_id       BIGINT          NULL,
    submission_count INT            NOT NULL DEFAULT 0,
    target_count    INT             NOT NULL DEFAULT 0,
    created_by      BIGINT          NULL,
    published_at    DATETIME,
    closed_at       DATETIME,
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at      DATETIME,
    PRIMARY KEY (id),
    CONSTRAINT fk_form_templates_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_form_templates_scope (scope_type, scope_id),
    INDEX idx_form_templates_status (status),
    INDEX idx_form_templates_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
