-- F06.1: ブログ記事・お知らせ本体テーブル
CREATE TABLE blog_posts (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_id                 BIGINT UNSIGNED NULL,
    organization_id         BIGINT UNSIGNED NULL,
    user_id                 BIGINT UNSIGNED NULL,
    social_profile_id       BIGINT UNSIGNED NULL,
    author_id               BIGINT UNSIGNED NULL,
    title                   VARCHAR(200) NOT NULL,
    slug                    VARCHAR(200) NOT NULL,
    body                    TEXT NOT NULL,
    excerpt                 VARCHAR(500) NULL,
    cover_image_url         VARCHAR(500) NULL,
    post_type               VARCHAR(15) NOT NULL DEFAULT 'BLOG',
    visibility              VARCHAR(30) NOT NULL DEFAULT 'MEMBERS_ONLY',
    priority                VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
    status                  VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_at            DATETIME NULL,
    self_review_deadline    DATETIME NULL,
    archive_at              DATETIME NULL,
    pinned                  BOOLEAN NOT NULL DEFAULT FALSE,
    allow_comments          BOOLEAN NOT NULL DEFAULT FALSE,
    target_type             VARCHAR(10) NOT NULL DEFAULT 'ALL',
    target_id               BIGINT UNSIGNED NULL,
    cross_post_to_timeline  BOOLEAN NOT NULL DEFAULT FALSE,
    timeline_post_id        BIGINT UNSIGNED NULL,
    rejection_reason        VARCHAR(500) NULL,
    view_count              INT UNSIGNED NOT NULL DEFAULT 0,
    reading_time_minutes    SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    version                 INT UNSIGNED NOT NULL DEFAULT 1,
    preview_token           VARCHAR(64) NULL,
    preview_token_expires_at DATETIME NULL,
    series_id               BIGINT UNSIGNED NULL,
    series_order            SMALLINT UNSIGNED NULL,
    created_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at              DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_bp_slug_team (team_id, slug, deleted_at),
    UNIQUE KEY uq_bp_slug_org (organization_id, slug, deleted_at),
    UNIQUE KEY uq_bp_slug_user (user_id, slug, deleted_at),
    INDEX idx_bp_team_status (team_id, status, published_at),
    INDEX idx_bp_org_status (organization_id, status, published_at),
    INDEX idx_bp_user_status (user_id, status, published_at),
    INDEX idx_bp_social_profile (social_profile_id, status, published_at),
    INDEX idx_bp_author (author_id),
    INDEX idx_bp_post_type (post_type, status, published_at),
    FULLTEXT INDEX ft_bp_title_body (title, body) WITH PARSER ngram,
    INDEX idx_bp_timeline_post (timeline_post_id),
    INDEX idx_bp_series (series_id, series_order),
    INDEX idx_bp_self_review (status, self_review_deadline),
    CONSTRAINT chk_bp_scope CHECK (
        (team_id IS NOT NULL AND organization_id IS NULL AND user_id IS NULL)
        OR (team_id IS NULL AND organization_id IS NOT NULL AND user_id IS NULL)
        OR (team_id IS NULL AND organization_id IS NULL AND user_id IS NOT NULL)
    ),
    CONSTRAINT chk_bp_social_profile CHECK (social_profile_id IS NULL OR user_id IS NOT NULL),
    CONSTRAINT fk_bp_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE,
    CONSTRAINT fk_bp_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_bp_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_bp_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_bp_series FOREIGN KEY (series_id) REFERENCES blog_post_series (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
