-- F09.14 重要事項説明書: 出力履歴（PDF/Excel/Word のメタデータ）
-- 設計書 §3 disclosure_exports テーブル定義に対応
CREATE TABLE disclosure_exports (
    id                            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scope_type                    VARCHAR(20)     NOT NULL,
    scope_id                      BIGINT UNSIGNED NOT NULL,
    draft_id                      BIGINT UNSIGNED NULL,
    template_id                   BIGINT UNSIGNED NOT NULL,
    template_code_snapshot        VARCHAR(50)     NOT NULL,
    template_version_snapshot     VARCHAR(20)     NOT NULL,
    output_format                 VARCHAR(10)     NOT NULL,
    shared_file_id                BIGINT UNSIGNED NOT NULL,
    target_dwelling_unit_id       BIGINT UNSIGNED NULL,
    requester_user_id             BIGINT UNSIGNED NOT NULL,
    recipient_note                VARCHAR(500)    NULL,
    referenced_package_ids        JSON            NULL,
    referenced_dwelling_unit_ids  JSON            NULL,
    data_snapshot                 JSON            NOT NULL,
    pdf_sha256                    CHAR(64)        NULL,
    circulation_document_id       BIGINT UNSIGNED NULL,
    expires_at                    DATETIME        NULL,
    created_at                    DATETIME        NOT NULL,
    deleted_at                    DATETIME        NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_de_draft        FOREIGN KEY (draft_id)                REFERENCES disclosure_form_drafts (id)    ON DELETE SET NULL,
    CONSTRAINT fk_de_template     FOREIGN KEY (template_id)             REFERENCES disclosure_form_templates (id) ON DELETE RESTRICT,
    CONSTRAINT fk_de_shared_file  FOREIGN KEY (shared_file_id)          REFERENCES shared_files (id)              ON DELETE RESTRICT,
    CONSTRAINT fk_de_dwelling     FOREIGN KEY (target_dwelling_unit_id) REFERENCES dwelling_units (id)            ON DELETE SET NULL,
    CONSTRAINT fk_de_requester    FOREIGN KEY (requester_user_id)       REFERENCES users (id)                     ON DELETE RESTRICT,
    CONSTRAINT fk_de_circulation  FOREIGN KEY (circulation_document_id) REFERENCES circulation_documents (id)     ON DELETE SET NULL,
    CONSTRAINT chk_de_scope_type CHECK (scope_type IN ('ORGANIZATION')),
    CONSTRAINT chk_de_output_format CHECK (output_format IN ('PDF','EXCEL','WORD')),
    INDEX idx_de_scope_time (scope_type, scope_id, created_at),
    INDEX idx_de_dwelling   (target_dwelling_unit_id),
    INDEX idx_de_template   (template_id),
    INDEX idx_de_expires    (expires_at),
    INDEX idx_de_requester  (requester_user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
