-- F09.13 物件履歴台帳: 集約ルート（1工事/1事故/1点検 = 1レコード）
-- 設計書 §3 property_work_packages テーブル定義に対応
CREATE TABLE property_work_packages (
    id                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scope_type             VARCHAR(20)     NOT NULL,
    scope_id               BIGINT UNSIGNED NOT NULL,
    dwelling_unit_id       BIGINT UNSIGNED NULL,
    work_type              VARCHAR(20)     NOT NULL,
    category               VARCHAR(50)     NULL,
    title                  VARCHAR(200)    NOT NULL,
    description            TEXT            NULL,
    incident_id            BIGINT UNSIGNED NULL,
    incident_date          DATE            NULL,
    incident_narrative     TEXT            NULL,
    planned_start_date     DATE            NULL,
    planned_end_date       DATE            NULL,
    actual_start_date      DATE            NULL,
    actual_end_date        DATE            NULL,
    vendor_id              BIGINT UNSIGNED NULL,
    vendor_name_snapshot   VARCHAR(150)    NULL,
    estimated_amount       BIGINT          NULL,
    contract_amount        BIGINT          NULL,
    actual_amount          BIGINT          NULL,
    currency               VARCHAR(3)      NOT NULL DEFAULT 'JPY',
    budget_transaction_id  BIGINT UNSIGNED NULL,
    timeline_post_id       BIGINT UNSIGNED NULL,
    warranty_until         DATE            NULL,
    is_disclosable         TINYINT(1)      NOT NULL DEFAULT 1,
    visibility             VARCHAR(20)     NOT NULL DEFAULT 'ADMINS_ONLY',
    status                 VARCHAR(20)     NOT NULL DEFAULT 'PLANNED',
    attachment_count       INT             NOT NULL DEFAULT 0,
    comment_count          INT             NOT NULL DEFAULT 0,
    tags                   JSON            NULL,
    created_by             BIGINT UNSIGNED NOT NULL,
    updated_by             BIGINT UNSIGNED NULL,
    version                BIGINT          NOT NULL DEFAULT 0,
    created_at             DATETIME        NOT NULL,
    updated_at             DATETIME        NOT NULL,
    deleted_at             DATETIME        NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_pwp_dwelling   FOREIGN KEY (dwelling_unit_id)       REFERENCES dwelling_units (id)        ON DELETE SET NULL,
    CONSTRAINT fk_pwp_incident   FOREIGN KEY (incident_id)            REFERENCES incidents (id)             ON DELETE SET NULL,
    CONSTRAINT fk_pwp_vendor     FOREIGN KEY (vendor_id)              REFERENCES vendors (id)               ON DELETE SET NULL,
    CONSTRAINT fk_pwp_budget_tx  FOREIGN KEY (budget_transaction_id)  REFERENCES budget_transactions (id)   ON DELETE SET NULL,
    CONSTRAINT fk_pwp_timeline   FOREIGN KEY (timeline_post_id)       REFERENCES timeline_posts (id)        ON DELETE SET NULL,
    CONSTRAINT fk_pwp_created_by FOREIGN KEY (created_by)             REFERENCES users (id)                 ON DELETE RESTRICT,
    CONSTRAINT fk_pwp_updated_by FOREIGN KEY (updated_by)             REFERENCES users (id)                 ON DELETE SET NULL,
    CONSTRAINT chk_pwp_scope_type CHECK (scope_type IN ('TEAM','ORGANIZATION')),
    CONSTRAINT chk_pwp_work_type CHECK (
        work_type IN ('RENOVATION','REPAIR','INCIDENT','INSPECTION','DISASTER','MEETING','OTHER')
    ),
    CONSTRAINT chk_pwp_status CHECK (
        status IN ('PLANNED','IN_PROGRESS','COMPLETED','CLOSED','CANCELLED')
    ),
    CONSTRAINT chk_pwp_visibility CHECK (
        visibility IN ('ADMINS_ONLY','MEMBERS_ONLY','MEMBERS_MASKED','PUBLIC_MASKED')
    ),
    CONSTRAINT chk_pwp_currency CHECK (currency REGEXP '^[A-Z]{3}$'),
    INDEX idx_pwp_scope_status   (scope_type, scope_id, status, deleted_at),
    INDEX idx_pwp_scope_type     (scope_type, scope_id, work_type, deleted_at),
    INDEX idx_pwp_dwelling       (dwelling_unit_id),
    INDEX idx_pwp_incident       (incident_id),
    INDEX idx_pwp_vendor         (vendor_id),
    INDEX idx_pwp_planned_dates  (scope_type, scope_id, planned_start_date),
    INDEX idx_pwp_actual_dates   (scope_type, scope_id, actual_end_date),
    INDEX idx_pwp_disclosable    (scope_type, scope_id, is_disclosable, actual_end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
