-- F08.1: 対外交流の募集投稿テーブル
CREATE TABLE match_requests (
    id                   BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    team_id              BIGINT UNSIGNED  NOT NULL,
    title                VARCHAR(100)     NOT NULL,
    description          TEXT             NULL,
    activity_type        ENUM('COMPETITION','PRACTICE','EXCHANGE','RECRUIT','OTHER') NOT NULL,
    activity_detail      VARCHAR(50)      NULL,
    category             ENUM('ELEMENTARY','JUNIOR_HIGH','HIGH_SCHOOL','UNIVERSITY','ADULT','SENIOR','ANY') NOT NULL DEFAULT 'ANY',
    visibility           ENUM('PLATFORM','ORGANIZATION') NOT NULL DEFAULT 'PLATFORM',
    prefecture_code      CHAR(2)          NOT NULL,
    city_code            CHAR(5)          NULL,
    venue_name           VARCHAR(200)     NULL,
    preferred_date_from  DATE             NULL,
    preferred_date_to    DATE             NULL,
    preferred_time_from  TIME             NULL,
    preferred_time_to    TIME             NULL,
    level                ENUM('BEGINNER','INTERMEDIATE','ADVANCED','ANY') NOT NULL DEFAULT 'ANY',
    min_participants     SMALLINT UNSIGNED NULL,
    max_participants     SMALLINT UNSIGNED NULL,
    status               ENUM('OPEN','MATCHED','CANCELLED','EXPIRED') NOT NULL DEFAULT 'OPEN',
    proposal_count       INT UNSIGNED     NOT NULL DEFAULT 0,
    expires_at           DATETIME         NULL,
    matched_proposal_id  BIGINT UNSIGNED  NULL,
    cancel_count         SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at           DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at           DATETIME         NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_mr_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    CONSTRAINT fk_mr_prefecture FOREIGN KEY (prefecture_code) REFERENCES prefectures(code),
    CONSTRAINT fk_mr_city FOREIGN KEY (city_code) REFERENCES cities(code),
    INDEX idx_mr_team (team_id, status, created_at),
    INDEX idx_mr_search (visibility, prefecture_code, city_code, activity_type, status, expires_at),
    INDEX idx_mr_category (category, status),
    INDEX idx_mr_level (level, status),
    INDEX idx_mr_expires (expires_at, status),
    FULLTEXT INDEX ft_mr_search (title, activity_detail)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
