-- F08.7: 組織ごとのカスタムテンプレート
CREATE TABLE tournament_templates (
    id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id   BIGINT UNSIGNED NOT NULL,
    source_preset_id  BIGINT UNSIGNED NULL,
    name              VARCHAR(100)    NOT NULL,
    description       VARCHAR(500)    NULL,
    icon              VARCHAR(30)     NULL,
    supported_formats JSON            NOT NULL,
    win_points        TINYINT UNSIGNED NOT NULL DEFAULT 3,
    draw_points       TINYINT UNSIGNED NOT NULL DEFAULT 1,
    loss_points       TINYINT UNSIGNED NOT NULL DEFAULT 0,
    has_draw          BOOLEAN         NOT NULL DEFAULT TRUE,
    has_sets          BOOLEAN         NOT NULL DEFAULT FALSE,
    sets_to_win       TINYINT UNSIGNED NULL,
    has_extra_time    BOOLEAN         NOT NULL DEFAULT FALSE,
    has_penalties     BOOLEAN         NOT NULL DEFAULT FALSE,
    score_unit_label  VARCHAR(20)     NOT NULL DEFAULT '点',
    bonus_point_rules JSON            NULL,
    version           BIGINT          NOT NULL DEFAULT 0,
    created_by        BIGINT UNSIGNED NOT NULL,
    created_at        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at        DATETIME        NULL,
    PRIMARY KEY (id),
    INDEX idx_tt_org (organization_id, deleted_at),
    CONSTRAINT fk_tt_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_tt_source_preset FOREIGN KEY (source_preset_id) REFERENCES system_tournament_presets (id) ON DELETE SET NULL,
    CONSTRAINT fk_tt_created_by FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
