-- F08.2: 支払い記録テーブル
CREATE TABLE member_payments (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                     BIGINT UNSIGNED NOT NULL,
    payment_item_id             BIGINT UNSIGNED NOT NULL,
    amount_paid                 DECIMAL(10,2)   NOT NULL,
    currency                    CHAR(3)         NOT NULL DEFAULT 'JPY',
    payment_method              ENUM('STRIPE', 'MANUAL') NOT NULL,
    status                      ENUM('PENDING', 'PAID', 'REFUNDED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    valid_from                  DATE            NULL,
    valid_until                 DATE            NULL,
    stripe_checkout_session_id  VARCHAR(100)    NULL,
    stripe_payment_intent_id    VARCHAR(100)    NULL,
    paid_at                     DATETIME        NULL,
    recorded_by                 BIGINT UNSIGNED NULL,
    note                        VARCHAR(500)    NULL,
    stripe_refund_id            VARCHAR(100)    NULL,
    stripe_receipt_url          VARCHAR(512)    NULL,
    refunded_at                 DATETIME        NULL,
    created_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_mp_user_item (user_id, payment_item_id),
    INDEX idx_mp_payment_item (payment_item_id),
    INDEX idx_mp_status (status),
    INDEX idx_mp_valid_until (valid_until),
    UNIQUE KEY uq_mp_checkout_session (stripe_checkout_session_id),
    UNIQUE KEY uq_mp_payment_intent (stripe_payment_intent_id),
    UNIQUE KEY uq_mp_refund (stripe_refund_id),
    CONSTRAINT fk_member_pay_user  FOREIGN KEY (user_id)         REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_mp_payment_item FOREIGN KEY (payment_item_id) REFERENCES payment_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_mp_recorded_by  FOREIGN KEY (recorded_by)     REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
