-- F08.4: 領収書発行 — 領収書テーブル
CREATE TABLE receipts (
    id                          BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    scope_type                  VARCHAR(20)      NOT NULL COMMENT 'スコープ（TEAM / ORGANIZATION）',
    scope_id                    BIGINT UNSIGNED  NOT NULL COMMENT 'スコープ ID',
    status                      VARCHAR(20)      NOT NULL DEFAULT 'ISSUED' COMMENT 'ステータス（DRAFT / ISSUED）',
    receipt_number              VARCHAR(50)      NULL     COMMENT '領収書番号（ISSUED 時に採番）',
    member_payment_id           BIGINT UNSIGNED  NULL     COMMENT 'FK → member_payments',
    recipient_user_id           BIGINT UNSIGNED  NULL     COMMENT 'FK → users。受領者',
    recipient_name              VARCHAR(200)     NOT NULL COMMENT '受領者名（宛名）',
    recipient_postal_code       VARCHAR(10)      NULL     COMMENT '受領者の郵便番号',
    recipient_address           VARCHAR(500)     NULL     COMMENT '受領者の住所',
    issuer_name                 VARCHAR(200)     NOT NULL COMMENT '発行者名（スナップショット）',
    issuer_postal_code          VARCHAR(10)      NULL     COMMENT '発行者郵便番号（スナップショット）',
    issuer_address              VARCHAR(500)     NULL     COMMENT '発行者住所（スナップショット）',
    issuer_phone                VARCHAR(20)      NULL     COMMENT '発行者電話番号（スナップショット）',
    is_qualified_invoice        BOOLEAN          NOT NULL DEFAULT FALSE COMMENT '適格請求書として発行されたか',
    invoice_registration_number VARCHAR(14)      NULL     COMMENT '発行時点の登録番号（スナップショット）',
    description                 VARCHAR(500)     NOT NULL COMMENT '但し書き',
    amount                      DECIMAL(10,0)    NOT NULL COMMENT '税込金額',
    tax_rate                    DECIMAL(4,2)     NOT NULL DEFAULT 10.00 COMMENT '適用税率（%）',
    tax_amount                  DECIMAL(10,0)    NOT NULL COMMENT '税額',
    amount_excl_tax             DECIMAL(10,0)    NOT NULL COMMENT '税抜金額',
    payment_method_label        VARCHAR(50)      NULL     COMMENT '支払い方法の表示名',
    payment_date                DATE             NOT NULL COMMENT '支払日',
    issued_at                   DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '発行日時',
    issued_by                   BIGINT UNSIGNED  NOT NULL COMMENT 'FK → users。発行した ADMIN',
    seal_stamp_log_id           BIGINT UNSIGNED  NULL     COMMENT 'FK → seal_stamp_logs',
    pdf_storage_key             VARCHAR(500)     NULL     COMMENT 'S3 上の PDF ファイルキー',
    schedule_id                 BIGINT UNSIGNED  NULL     COMMENT 'FK → schedules。但し書き自動取得元',
    voided_at                   DATETIME         NULL     COMMENT '無効化日時',
    voided_by                   BIGINT UNSIGNED  NULL     COMMENT 'FK → users。無効化した ADMIN',
    voided_reason               VARCHAR(500)     NULL     COMMENT '無効化理由',
    created_at                  DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_r_receipt_number (scope_type, scope_id, receipt_number),
    INDEX idx_r_scope (scope_type, scope_id, issued_at DESC),
    INDEX idx_r_recipient (recipient_user_id, issued_at DESC),
    INDEX idx_r_payment (member_payment_id),
    INDEX idx_r_schedule (schedule_id),
    FULLTEXT INDEX ft_r_recipient (recipient_name),
    CONSTRAINT fk_r_recipient_user FOREIGN KEY (recipient_user_id) REFERENCES users (id),
    CONSTRAINT fk_r_issued_by FOREIGN KEY (issued_by) REFERENCES users (id),
    CONSTRAINT fk_r_voided_by FOREIGN KEY (voided_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='発行済み領収書';
