-- F08.7: 対戦カード
CREATE TABLE tournament_matches (
    id                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    matchday_id            BIGINT UNSIGNED NOT NULL,
    home_participant_id    BIGINT UNSIGNED NULL,
    away_participant_id    BIGINT UNSIGNED NULL,
    match_number           SMALLINT UNSIGNED NULL,
    scheduled_datetime     DATETIME        NULL,
    venue                  VARCHAR(200)    NULL,
    home_score             SMALLINT UNSIGNED NULL,
    away_score             SMALLINT UNSIGNED NULL,
    home_extra_score       SMALLINT UNSIGNED NULL,
    away_extra_score       SMALLINT UNSIGNED NULL,
    home_penalty_score     SMALLINT UNSIGNED NULL,
    away_penalty_score     SMALLINT UNSIGNED NULL,
    winner_participant_id  BIGINT UNSIGNED NULL,
    result                 ENUM('HOME_WIN','AWAY_WIN','DRAW','PENDING','CANCELLED','BYE','FORFEIT_HOME_WIN','FORFEIT_AWAY_WIN') NOT NULL DEFAULT 'PENDING',
    leg                    TINYINT UNSIGNED NOT NULL DEFAULT 1,
    next_match_id          BIGINT UNSIGNED NULL,
    next_match_slot        ENUM('HOME','AWAY') NULL,
    notes                  TEXT            NULL,
    schedule_id            BIGINT UNSIGNED NULL,
    version                BIGINT          NOT NULL DEFAULT 0,
    status                 ENUM('SCHEDULED','IN_PROGRESS','COMPLETED','POSTPONED','CANCELLED') NOT NULL DEFAULT 'SCHEDULED',
    created_at             DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_tmatch_matchday (matchday_id, match_number),
    INDEX idx_tmatch_home (home_participant_id, status),
    INDEX idx_tmatch_away (away_participant_id, status),
    INDEX idx_tmatch_schedule (scheduled_datetime, status),
    INDEX idx_tmatch_next (next_match_id),
    CONSTRAINT fk_tmatch_matchday FOREIGN KEY (matchday_id) REFERENCES tournament_matchdays (id) ON DELETE CASCADE,
    CONSTRAINT fk_tmatch_home FOREIGN KEY (home_participant_id) REFERENCES tournament_participants (id),
    CONSTRAINT fk_tmatch_away FOREIGN KEY (away_participant_id) REFERENCES tournament_participants (id),
    CONSTRAINT fk_tmatch_winner FOREIGN KEY (winner_participant_id) REFERENCES tournament_participants (id),
    CONSTRAINT fk_tmatch_next FOREIGN KEY (next_match_id) REFERENCES tournament_matches (id) ON DELETE SET NULL,
    CONSTRAINT fk_tmatch_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE SET NULL,
    CONSTRAINT chk_tmatch_diff_teams CHECK (home_participant_id IS NULL OR away_participant_id IS NULL OR home_participant_id != away_participant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
