-- F08.5: 回数券決済記録テーブル
CREATE TABLE ticket_payments (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_id                     BIGINT UNSIGNED NOT NULL,
    user_id                     BIGINT UNSIGNED NOT NULL,
    product_id                  BIGINT UNSIGNED NOT NULL,
    payment_method              VARCHAR(20)     NOT NULL,
    amount                      INTEGER         NOT NULL,
    stripe_checkout_session_id  VARCHAR(200)    NULL,
    stripe_payment_intent_id    VARCHAR(200)    NULL,
    stripe_refund_id            VARCHAR(200)    NULL,
    status                      VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    refund_amount               INTEGER         NULL,
    recorded_by                 BIGINT UNSIGNED NULL,
    paid_at                     DATETIME        NULL,
    webhook_received_at         DATETIME        NULL,
    note                        VARCHAR(500)    NULL,
    created_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_tpay_team (team_id, status, created_at DESC),
    INDEX idx_tpay_user (user_id, status),
    UNIQUE KEY uq_tpay_session (stripe_checkout_session_id),
    INDEX idx_tpay_intent (stripe_payment_intent_id),
    CONSTRAINT fk_tpay_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_tpay_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_tpay_product FOREIGN KEY (product_id) REFERENCES ticket_products(id),
    CONSTRAINT fk_tpay_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
