-- F08.7: 大会・リーグのインスタンス
CREATE TABLE tournaments (
    id                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id          BIGINT UNSIGNED NOT NULL,
    template_id              BIGINT UNSIGNED NULL,
    previous_tournament_id   BIGINT UNSIGNED NULL,
    name                     VARCHAR(200)    NOT NULL,
    description              TEXT            NULL,
    format                   ENUM('LEAGUE','KNOCKOUT','GROUP_KNOCKOUT') NOT NULL,
    season                   VARCHAR(50)     NULL,
    start_date               DATE            NULL,
    end_date                 DATE            NULL,
    win_points               TINYINT UNSIGNED NOT NULL DEFAULT 3,
    draw_points              TINYINT UNSIGNED NOT NULL DEFAULT 1,
    loss_points              TINYINT UNSIGNED NOT NULL DEFAULT 0,
    has_draw                 BOOLEAN         NOT NULL DEFAULT TRUE,
    has_sets                 BOOLEAN         NOT NULL DEFAULT FALSE,
    sets_to_win              TINYINT UNSIGNED NULL,
    has_extra_time           BOOLEAN         NOT NULL DEFAULT FALSE,
    has_penalties            BOOLEAN         NOT NULL DEFAULT FALSE,
    score_unit_label         VARCHAR(20)     NOT NULL DEFAULT '点',
    bonus_point_rules        JSON            NULL,
    league_round_type        ENUM('SINGLE','DOUBLE') NOT NULL DEFAULT 'SINGLE',
    knockout_legs            TINYINT UNSIGNED NOT NULL DEFAULT 1,
    visibility               ENUM('PUBLIC','MEMBERS_ONLY') NOT NULL DEFAULT 'MEMBERS_ONLY',
    status                   ENUM('DRAFT','OPEN','IN_PROGRESS','COMPLETED','CANCELLED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    version                  BIGINT          NOT NULL DEFAULT 0,
    created_by               BIGINT UNSIGNED NOT NULL,
    created_at               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at               DATETIME        NULL,
    PRIMARY KEY (id),
    INDEX idx_t_org_status (organization_id, status, deleted_at),
    INDEX idx_t_season (organization_id, season),
    INDEX idx_t_visibility (visibility, status, deleted_at),
    INDEX idx_t_prev (previous_tournament_id),
    CONSTRAINT fk_t_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_t_template FOREIGN KEY (template_id) REFERENCES tournament_templates (id) ON DELETE SET NULL,
    CONSTRAINT fk_t_previous FOREIGN KEY (previous_tournament_id) REFERENCES tournaments (id) ON DELETE SET NULL,
    CONSTRAINT fk_t_created_by FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
