-- F09.8: コルクボードカード
CREATE TABLE corkboard_cards (
    id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    corkboard_id      BIGINT UNSIGNED NOT NULL,
    card_type         VARCHAR(20)     NOT NULL,
    reference_type    VARCHAR(30)     NULL,
    reference_id      BIGINT UNSIGNED NULL,
    content_snapshot  TEXT            NULL,
    title             VARCHAR(200)    NULL,
    body              TEXT            NULL,
    url               VARCHAR(2000)   NULL,
    og_title          VARCHAR(200)    NULL,
    og_image_url      VARCHAR(500)    NULL,
    og_description    VARCHAR(500)    NULL,
    color_label       VARCHAR(10)     NOT NULL DEFAULT 'NONE',
    card_size         VARCHAR(10)     NOT NULL DEFAULT 'MEDIUM',
    position_x        INT             NOT NULL DEFAULT 0,
    position_y        INT             NOT NULL DEFAULT 0,
    z_index           INT             NOT NULL DEFAULT 0,
    user_note         TEXT            NULL,
    auto_archive_at   DATETIME        NULL,
    is_archived       BOOLEAN         NOT NULL DEFAULT FALSE,
    created_by        BIGINT UNSIGNED NOT NULL,
    deleted_at        DATETIME        NULL,
    created_at        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_cc_board_active (corkboard_id, is_archived, deleted_at),
    INDEX idx_cc_reference (reference_type, reference_id),
    INDEX idx_cc_archive (is_archived, auto_archive_at),
    CONSTRAINT fk_cc_corkboard FOREIGN KEY (corkboard_id) REFERENCES corkboards (id) ON DELETE CASCADE,
    CONSTRAINT fk_cc_created_by FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
