-- F09.5 共用施設予約: 予約
CREATE TABLE facility_bookings (
    id                  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    facility_id         BIGINT UNSIGNED NOT NULL,
    booked_by           BIGINT UNSIGNED NOT NULL,
    created_by_admin    BIGINT UNSIGNED NULL,
    booking_date        DATE            NOT NULL,
    check_out_date      DATE            NULL,
    stay_nights         SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    time_from           TIME            NOT NULL,
    time_to             TIME            NOT NULL,
    slot_count          SMALLINT UNSIGNED NOT NULL,
    purpose             VARCHAR(500)    NULL,
    attendee_count      SMALLINT UNSIGNED NULL,
    usage_fee           DECIMAL(10,0)   NOT NULL DEFAULT 0,
    equipment_fee       DECIMAL(10,0)   NOT NULL DEFAULT 0,
    total_fee           DECIMAL(10,0)   NOT NULL DEFAULT 0,
    status              ENUM('PENDING_APPROVAL','CONFIRMED','CHECKED_IN','COMPLETED',
                             'CANCELLED','REJECTED','NO_SHOW') NOT NULL DEFAULT 'PENDING_APPROVAL',
    admin_comment       VARCHAR(500)    NULL,
    approved_by         BIGINT UNSIGNED NULL,
    approved_at         DATETIME        NULL,
    checked_in_at       DATETIME        NULL,
    completed_at        DATETIME        NULL,
    cancelled_at        DATETIME        NULL,
    cancelled_by        BIGINT UNSIGNED NULL,
    cancellation_reason VARCHAR(500)    NULL,
    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_fb_facility_date (facility_id, booking_date),
    INDEX idx_fb_user (booked_by),
    INDEX idx_fb_date_status (booking_date, status),
    CONSTRAINT fk_fb_facility FOREIGN KEY (facility_id) REFERENCES shared_facilities(id),
    CONSTRAINT fk_fb_booked_by FOREIGN KEY (booked_by) REFERENCES users(id),
    CONSTRAINT fk_fb_created_by_admin FOREIGN KEY (created_by_admin) REFERENCES users(id),
    CONSTRAINT fk_fb_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT fk_fb_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
