package com.mannschaft.app.common.activityschedule;

import com.mannschaft.app.activity.ActivityMapper;
import com.mannschaft.app.activity.dto.ActivityParticipantResponse;
import com.mannschaft.app.activity.dto.ActivityRecordResponse;
import com.mannschaft.app.activity.dto.AddParticipantsRequest;
import com.mannschaft.app.activity.dto.RemoveParticipantsRequest;
import com.mannschaft.app.activity.dto.UpdateActivityRequest;
import com.mannschaft.app.activity.service.ActivityDetailService;
import com.mannschaft.app.activity.service.ActivityResultService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

/** 認可を共通層で先行し、同じTXで活動の版検証と更新を実行する。 */
@Service
@RequiredArgsConstructor
public class ActivityMutationFacade {
    private final ActivityDetailService details;
    private final ActivityResultService activities;
    private final ActivityMapper mapper;
    private final com.mannschaft.app.schedule.service.ScheduleActivitySourceService sources;
    private final com.mannschaft.app.activity.service.ActivityDeletionService deletion;

    /** 保存済みactualの削除はsource閲覧を要求せず、source→activityのlock順だけ共有する。 */
    @Transactional
    public void delete(Long id, Long userId) {
        var reference = details.deletionReference(id, userId);
        if (reference.autoGeneratedFromSchedule()) {
            sources.lockStoredSource(reference.scheduleId());
            deletion.deleteAutomatic(reference);
        } else {
            activities.deleteActivity(id, userId);
        }
    }

    @Transactional
    public ActivityRecordResponse duplicate(Long id, Long userId,
            com.mannschaft.app.activity.dto.DuplicateActivityRequest request) {
        // autoのmetadata読取を複製によるactual取得へ昇格させない。manualの既存所属契約は維持する。
        details.requireActualForAutomatic(id, userId);
        return mapper.toActivityRecordResponse(activities.duplicateActivity(id, userId, request));
    }

    @Transactional
    public ActivityRecordResponse publish(Long id, Long userId, Long version) {
        details.requireEditPermission(id, userId);
        return activities.publishActivityVersioned(id, userId, version);
    }

    @Transactional
    public ActivityRecordResponse update(Long id, Long userId, UpdateActivityRequest request) {
        details.requireEditPermission(id, userId);
        return mapper.toActivityRecordResponse(activities.updateActivity(id, userId, request));
    }

    @Transactional
    public List<ActivityParticipantResponse> addParticipants(Long id, Long userId, AddParticipantsRequest request) {
        details.requireEditPermission(id, userId);
        return activities.addParticipants(id, userId, request);
    }

    @Transactional
    public List<ActivityParticipantResponse> removeParticipants(Long id, Long userId, RemoveParticipantsRequest request) {
        details.requireEditPermission(id, userId);
        return activities.removeParticipants(id, userId, request);
    }
}
