package com.mannschaft.app.common.activityschedule;

import com.mannschaft.app.activity.visibility.ActivityResultVisibilityProjection;
import com.mannschaft.app.activity.service.ActivityScopeAccessGuard;
import com.mannschaft.app.schedule.service.ScheduleActivityVisibilityService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import java.util.List;

/** auto実績だけに恒久source ACLを適用する共通読取段取り。metadata権限は含めない。 */
@Service
@RequiredArgsConstructor
public class AutomaticActivityActualPolicy {
    private final ScheduleActivityVisibilityService scheduleVisibility;
    private final ActivityScopeAccessGuard activityAccess;

    public List<ActivityResultVisibilityProjection> filterEligible(List<ActivityResultVisibilityProjection> rows,
                                                                   Long viewerUserId) {
        var automatic = rows.stream().filter(ActivityResultVisibilityProjection::autoGeneratedFromSchedule).toList();
        if (automatic.isEmpty()) return rows;
        var sourceIds = automatic.stream().map(r -> r.scheduleId()).filter(java.util.Objects::nonNull)
                .collect(java.util.stream.Collectors.toSet());
        var sources = scheduleVisibility.visibleSources(sourceIds, viewerUserId);
        boolean systemAdmin = activityAccess.isSystemAdmin(viewerUserId);
        java.util.Map<com.mannschaft.app.common.visibility.ScopeKey, Boolean> member = new java.util.HashMap<>();
        java.util.Map<com.mannschaft.app.common.visibility.ScopeKey, Boolean> admin = new java.util.HashMap<>();
        return rows.stream().filter(r -> {
            if (!r.autoGeneratedFromSchedule()) return true;
            var type = com.mannschaft.app.activity.ActivityScopeType.valueOf(r.scopeType());
            var scope = new com.mannschaft.app.common.visibility.ScopeKey(r.scopeType(), r.scopeId());
            boolean belongs = viewerUserId != null && member.computeIfAbsent(scope,
                    s -> activityAccess.isMember(viewerUserId, type, r.scopeId()));
            if (systemAdmin && !belongs) return false;
            boolean editor = belongs
                    && (java.util.Objects.equals(viewerUserId, r.authorUserId()) || admin.computeIfAbsent(scope,
                    s -> activityAccess.isAdminOrAbove(viewerUserId, type, r.scopeId())));
            if (editor) return true;
            if (r.status() == com.mannschaft.app.activity.ActivityStatus.DRAFT) return false;
            var source = sources.get(r.scheduleId());
            return source != null && java.util.Objects.equals(source.scopeType(), r.scopeType())
                    && java.util.Objects.equals(source.scopeId(), r.scopeId());
        }).toList();
    }
}
